Disco-C: src/discord/structures/attachment.h File Reference
attachment.h File Reference
#include <cJSON/cJSON.h>
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_attachment
Functions
void * disco_create_attachment_struct_json (cJSON *data)
Creates an attachment structure from a given JSON.
void disco_destroy_attachment (struct discord_attachment *attachment)
Destroys the given structure and frees the pointer.
Function Documentation
disco_create_attachment_struct_json()
void* disco_create_attachment_struct_json (cJSON * data)
Creates an attachment structure from a given JSON.
Parameters
data
Returns
void* discord_attachment struct
References discord_attachment::content_type, discord_attachment::description, discord_attachment::ephemeral, discord_attachment::filename, get_bool_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_attachment::height, discord_attachment::id, discord_attachment::proxy_url, discord_attachment::size, discord_attachment::url, and discord_attachment::width.
Referenced by disco_create_message_struct_json().
disco_destroy_attachment()
void disco_destroy_attachment (struct discord_attachment * attachment)
Destroys the given structure and frees the pointer.
Parameters
attachment
References discord_attachment::content_type, discord_attachment::description, discord_attachment::filename, discord_attachment::proxy_url, and discord_attachment::url.
Referenced by disco_destroy_message().