Disco-C: src/utils/cache.h File Reference
cache.h File Reference
#include "../discord/structures/channel.h"
#include "../discord/structures/guild.h"
#include "../discord/structures/message.h"
#include <hashmap.h/hashmap.h>
Typedefs
typedef void(* cache_destroy_callback_fn) (enum Disco_Cache_Type type, void *structure)
Function that will be called if the max cache size is reached.
Enumerations
enum Disco_Cache_Type { DISCO_CHANNEL_CACHE, DISCO_MESSAGE_CACHE, DISCO_GUILD_CACHE }
Functions
int disco_cache_init (int message_cache_size, int channel_cache_size, int guild_cache_size, cache_destroy_callback_fn callback)
Initializes all the caches.
void disco_cache_destroy (void)
Cleans up the cache and frees all the structs it contains.
int disco_cache_set_message (struct discord_message *message)
Adds a message to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
struct discord_message * disco_cache_get_message (uint64_t id)
Retreives a message by ID in the cache.
void disco_cache_delete_message (uint64_t id)
Removes a message from the cache and deallocates the message from memory.
int disco_cache_set_channel (struct discord_channel *channel)
Adds a channel to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
struct discord_channel * disco_cache_get_channel (uint64_t id)
Retreives a channel by ID in the cache.
void disco_cache_delete_channel (uint64_t id)
Removes a channel from the cache and deallocates the channel from memory.
int disco_cache_set_guild (struct discord_guild *guild)
Adds a guild to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
struct discord_guild * disco_cache_get_guild (uint64_t id)
Retreives a guild by ID in the cache.
void disco_cache_delete_guild (uint64_t id)
Removes a guild from the cache and deallocates the guild from memory.
Typedef Documentation
cache_destroy_callback_fn
typedef void(* cache_destroy_callback_fn) (enum Disco_Cache_Type type, void *structure)
Function that will be called if the max cache size is reached.
This allows the user to choose what do with the structure however they want. The user can choose to simply destroy the structure or they can also add the structure back into the cache based on a condition (Note this can result in an infinite loop if one chooses to add the element back in the queue resulting in a new element being removed).
Parameters
type Type of structure
structure Pointer to the actual structure
Enumeration Type Documentation
Disco_Cache_Type
enum Disco_Cache_Type
Enumerator
DISCO_CHANNEL_CACHE
DISCO_MESSAGE_CACHE
DISCO_GUILD_CACHE
Function Documentation
disco_cache_delete_channel()
void disco_cache_delete_channel (uint64_t id)
Removes a channel from the cache and deallocates the channel from memory.
Parameters
id ID of the channel to remove
References disco_cache_delete(), and DISCO_CHANNEL_CACHE.
Referenced by disco_cache_set().
disco_cache_delete_guild()
void disco_cache_delete_guild (uint64_t id)
Removes a guild from the cache and deallocates the guild from memory.
Parameters
id ID of the guild to remove
References disco_cache_delete(), and DISCO_GUILD_CACHE.
Referenced by disco_cache_set().
disco_cache_delete_message()
void disco_cache_delete_message (uint64_t id)
Removes a message from the cache and deallocates the message from memory.
Parameters
id ID of the message to remove
References disco_cache_delete(), and DISCO_MESSAGE_CACHE.
Referenced by disco_cache_set().
disco_cache_destroy()
void disco_cache_destroy (void)
Cleans up the cache and frees all the structs it contains.
References node::alloc_id, channels_map, channels_queue, node::data, destroy_item_callback_fn, DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, guilds_map, guilds_queue, buffer::head, messages_map, messages_queue, node::pointers, and buffer::size.
Referenced by disco_start_bot().
disco_cache_get_channel()
struct discord_channel* disco_cache_get_channel (uint64_t id)
Retreives a channel by ID in the cache.
Parameters
id
Returns
struct discord_channel* Pointer to the channel struct. NULL if the channel is not in the cache.
References disco_cache_get(), and DISCO_CHANNEL_CACHE.
Referenced by event_handle().
disco_cache_get_guild()
struct discord_guild* disco_cache_get_guild (uint64_t id)
Retreives a guild by ID in the cache.
Parameters
id
Returns
struct discord_guild* Pointer to the guild struct. NULL if the guild is not in the cache.
References disco_cache_get(), and DISCO_GUILD_CACHE.
disco_cache_get_message()
struct discord_message* disco_cache_get_message (uint64_t id)
Retreives a message by ID in the cache.
Parameters
id
Returns
struct discord_message* Pointer to the message struct. NULL if the message is not in the cache.
References disco_cache_get(), and DISCO_MESSAGE_CACHE.
Referenced by event_handle().
disco_cache_init()
int disco_cache_init (int message_cache_size, int channel_cache_size, int guild_cache_size, cache_destroy_callback_fn callback)
Initializes all the caches.
Should be called once when starting up the bot. Once the max cache size is reached, the oldest messages/channels/guilds will start to be cleaned up. Any time an object is edited on Discord, its "TTL" will be renewed in the cache.
The minimum cache size is 2, because edits require both the old and new object in the cache. Any number lower than 2 will result in the cache being set to 2.
Parameters
message_cache_size Maximum amount of messages the cache can hold (> 1)
channel_cach_size Maximum amount of channels the cache can hold (> 1)
guild_cache_size Maximum amount of guilds the cache can hold (> 1)
callback Callback that is called whenever a structure is taken out of the cache. It is up to the user if the structure should be freed or what happens to it. Keep it NULL to have the structures be freed up.
Returns
int 0 if succeeded, 1 otherwise
References channels_map, channels_queue, d_log_err, d_log_notice, default_destroy_callback(), destroy_item_callback_fn, guilds_map, guilds_queue, buffer::head, max_channel_cache_size, max_guild_cache_size, max_message_cache_size, messages_map, messages_queue, and buffer::size.
Referenced by disco_start_bot().
disco_cache_set_channel()
int disco_cache_set_channel (struct discord_channel * channel)
Adds a channel to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
Parameters
channel
Returns
int
References disco_cache_set(), and DISCO_CHANNEL_CACHE.
Referenced by event_handle().
disco_cache_set_guild()
int disco_cache_set_guild (struct discord_guild * guild)
Adds a guild to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
Parameters
guild
Returns
int
References disco_cache_set(), and DISCO_GUILD_CACHE.
disco_cache_set_message()
int disco_cache_set_message (struct discord_message * message)
Adds a message to the cache by ID. If it already exists in cache, it frees and overwrites the previous entry.
Parameters
message
Returns
int
References disco_cache_set(), and DISCO_MESSAGE_CACHE.
Referenced by event_handle().