Disco-C: src/utils/cache.c File Reference
cache.c File Reference
This file handles a cache for messages, guilds and channels. Structures are kept alive in the queue even if a new structure for the ID is created (message was edited). The structure will be cleaned up though if it is at the beginning of the queue and the max cache size is reached. struct.
#include <sys/queue.h>
#include <utils/cache.h>
#include <utils/disco_logging.h>
Data Structures
struct node
struct buffer
Functions
static void default_destroy_callback (enum Disco_Cache_Type type, void *structure)
int discord_cache_init (int message_cache_size, int channel_cache_size, int guild_cache_size, cache_destroy_callback_fn callback)
Initializes all the caches.
void discord_cache_destroy (void)
Cleans up the cache and frees all the structs it contains.
int discord_cache_set (enum Disco_Cache_Type type, void *cont)
void * discord_cache_get (enum Disco_Cache_Type type, uint64_t id)
void discord_cache_delete (enum Disco_Cache_Type type, uint64_t id)
int discord_cache_set_message (struct discord_message *message)
Adds a message to the cache by ID.
struct discord_message * discord_cache_get_message (uint64_t id)
Retreives a message by ID in the cache.
void discord_cache_delete_message (uint64_t id)
Removes a message from the cache and deallocates the message from memory.
int discord_cache_set_channel (struct discord_channel *channel)
Adds a channel to the cache by ID.
struct discord_channel * discord_cache_get_channel (uint64_t id)
Retreives a channel by ID in the cache.
void discord_cache_delete_channel (uint64_t id)
Removes a channel from the cache and deallocates the channel from memory.
int discord_cache_set_guild (struct discord_guild *guild)
Adds a guild to the cache by ID.
struct discord_guild * discord_cache_get_guild (uint64_t id)
Retreives a guild by ID in the cache.
void discord_cache_delete_guild (uint64_t id)
Removes a guild from the cache and deallocates the guild from memory.
Variables
static struct hashmap_s messages_map
static struct buffer messages_queue
static int max_message_cache_size
static struct hashmap_s channels_map
static struct buffer channels_queue
static int max_channel_cache_size
static struct hashmap_s guilds_map
static struct buffer guilds_queue
static int max_guild_cache_size
static cache_destroy_callback_fn destroy_item_callback_fn
Detailed Description
This file handles a cache for messages, guilds and channels. Structures are kept alive in the queue even if a new structure for the ID is created (message was edited). The structure will be cleaned up though if it is at the beginning of the queue and the max cache size is reached. struct.
Version
0.1
Date
2022-06-21
Copyright
Copyright (c) 2022
Function Documentation
default_destroy_callback()
static void default_destroy_callback (enum Disco_Cache_Type type, void * structure) static
References DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, discord_destroy_channel(), discord_destroy_guild(), and discord_destroy_message().
Referenced by discord_cache_init().
discord_cache_delete()
void discord_cache_delete (enum Disco_Cache_Type type, uint64_t id)
References node::alloc_id, channels_map, channels_queue, node::data, destroy_item_callback_fn, DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, guilds_map, guilds_queue, buffer::head, messages_map, messages_queue, node::pointers, and buffer::size.
Referenced by discord_cache_delete_channel(), discord_cache_delete_guild(), and discord_cache_delete_message().
discord_cache_delete_channel()
void discord_cache_delete_channel (uint64_t id)
Removes a channel from the cache and deallocates the channel from memory.
Parameters
id ID of the channel to remove
References DISCO_CHANNEL_CACHE, and discord_cache_delete().
Referenced by discord_cache_set().
discord_cache_delete_guild()
void discord_cache_delete_guild (uint64_t id)
Removes a guild from the cache and deallocates the guild from memory.
Parameters
id ID of the guild to remove
References DISCO_GUILD_CACHE, and discord_cache_delete().
Referenced by discord_cache_set().
discord_cache_delete_message()
void discord_cache_delete_message (uint64_t id)
Removes a message from the cache and deallocates the message from memory.
Parameters
id ID of the message to remove
References DISCO_MESSAGE_CACHE, and discord_cache_delete().
Referenced by discord_cache_set().
discord_cache_destroy()
void discord_cache_destroy (void)
Cleans up the cache and frees all the structs it contains.
References node::alloc_id, channels_map, channels_queue, node::data, destroy_item_callback_fn, DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, guilds_map, guilds_queue, buffer::head, messages_map, messages_queue, node::pointers, and buffer::size.
Referenced by discord_start_bot().
discord_cache_get()
void* discord_cache_get (enum Disco_Cache_Type type, uint64_t id)
References channels_map, channels_queue, node::data, DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, guilds_map, guilds_queue, buffer::head, messages_map, messages_queue, and node::pointers.
Referenced by discord_cache_get_channel(), discord_cache_get_guild(), and discord_cache_get_message().
discord_cache_get_channel()
struct discord_channel* discord_cache_get_channel (uint64_t id)
Retreives a channel by ID in the cache.
Parameters
id
Returns
struct discord_channel* Pointer to the channel struct. NULL if the channel is not in the cache.
References DISCO_CHANNEL_CACHE, and discord_cache_get().
Referenced by event_handle().
discord_cache_get_guild()
struct discord_guild* discord_cache_get_guild (uint64_t id)
Retreives a guild by ID in the cache.
Parameters
id
Returns
struct discord_guild* Pointer to the guild struct. NULL if the guild is not in the cache.
References DISCO_GUILD_CACHE, and discord_cache_get().
discord_cache_get_message()
struct discord_message* discord_cache_get_message (uint64_t id)
Retreives a message by ID in the cache.
Parameters
id
Returns
struct discord_message* Pointer to the message struct. NULL if the message is not in the cache.
References DISCO_MESSAGE_CACHE, and discord_cache_get().
Referenced by event_handle().
discord_cache_init()
int discord_cache_init (int message_cache_size, int channel_cache_size, int guild_cache_size, cache_destroy_callback_fn callback)
Initializes all the caches.
Should be called once when starting up the bot. Once the max cache size is reached, the oldest messages/channels/guilds will start to be cleaned up. Any time an object is edited on Discord, its "TTL" will be renewed in the cache.
The minimum cache size is 2, because edits require both the old and new object in the cache. Any number lower than 2 will result in the cache being set to 2.
Parameters
message_cache_size Maximum amount of messages the cache can hold (> 1)
channel_cache_size Maximum amount of channels the cache can hold (> 1)
guild_cache_size Maximum amount of guilds the cache can hold (> 1)
callback Callback that is called whenever a structure is taken out of the cache. It is up to the user if the structure should be freed or what happens to it. Keep it NULL to have the structures be freed up.
Returns
int 0 if succeeded, 1 otherwise
References channels_map, channels_queue, d_log_err, d_log_notice, default_destroy_callback(), destroy_item_callback_fn, guilds_map, guilds_queue, buffer::head, max_channel_cache_size, max_guild_cache_size, max_message_cache_size, messages_map, messages_queue, and buffer::size.
Referenced by discord_start_bot().
discord_cache_set()
int discord_cache_set (enum Disco_Cache_Type type, void * cont)
References node::alloc_id, channels_map, channels_queue, d_log_debug, d_log_err, d_log_notice, node::data, DISCO_CHANNEL_CACHE, DISCO_GUILD_CACHE, DISCO_MESSAGE_CACHE, discord_cache_delete_channel(), discord_cache_delete_guild(), discord_cache_delete_message(), guilds_map, guilds_queue, buffer::head, max_channel_cache_size, max_guild_cache_size, max_message_cache_size, messages_map, messages_queue, node::pointers, and buffer::size.
Referenced by discord_cache_set_channel(), discord_cache_set_guild(), and discord_cache_set_message().
discord_cache_set_channel()
int discord_cache_set_channel (struct discord_channel * channel)
Adds a channel to the cache by ID.
If it already exists in cache, it frees and overwrites the previous entry.
Parameters
channel
Returns
int
References DISCO_CHANNEL_CACHE, and discord_cache_set().
Referenced by event_handle().
discord_cache_set_guild()
int discord_cache_set_guild (struct discord_guild * guild)
Adds a guild to the cache by ID.
If it already exists in cache, it frees and overwrites the previous entry.
Parameters
guild
Returns
int
References DISCO_GUILD_CACHE, and discord_cache_set().
discord_cache_set_message()
int discord_cache_set_message (struct discord_message * message)
Adds a message to the cache by ID.
If it already exists in cache, it frees and overwrites the previous entry.
Parameters
message
Returns
int
References DISCO_MESSAGE_CACHE, and discord_cache_set().
Referenced by event_handle().
Variable Documentation
channels_map
struct hashmap_s channels_map static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().
channels_queue
struct buffer channels_queue static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().
destroy_item_callback_fn
cache_destroy_callback_fn destroy_item_callback_fn static
Referenced by discord_cache_delete(), discord_cache_destroy(), and discord_cache_init().
guilds_map
struct hashmap_s guilds_map static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().
guilds_queue
struct buffer guilds_queue static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().
max_channel_cache_size
int max_channel_cache_size static
Referenced by discord_cache_init(), and discord_cache_set().
max_guild_cache_size
int max_guild_cache_size static
Referenced by discord_cache_init(), and discord_cache_set().
max_message_cache_size
int max_message_cache_size static
Referenced by discord_cache_init(), and discord_cache_set().
messages_map
struct hashmap_s messages_map static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().
messages_queue
struct buffer messages_queue static
Referenced by discord_cache_delete(), discord_cache_destroy(), discord_cache_get(), discord_cache_init(), and discord_cache_set().