Disco-C: src/discord/structures/channel.h File Reference
channel.h File Reference
#include "permission.h"
#include "thread.h"
#include "user.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_channel
struct discord_channel_mention
Enumerations
enum Discord_Channel_Type {
CHANNEL_GUILD_TEXT = 0, CHANNEL_DM = 1, CHANNEL_GROUP_DM = 1, CHANNEL_GUILD_VOICE = 2,
CHANNEL_GUILD_CATEGORY = 4, CHANNEL_GUILD_NEWS = 5, CHANNEL_GUILD_NEWS_THREAD = 10, CHANNEL_GUILD_PUBLIC_THREAD = 11,
CHANNEL_GUILD_PRIVATE_THREAD = 12, CHANNEL_GUILD_STAGE_VOICE = 13, CHANNEL_GUILD_DIRECTORY = 14, CHANNEL_GUILD_FORUM = 15
}
Functions
void * disco_create_channel_struct_json (cJSON *data)
Creates a channel structure from a given JSON.
void disco_destroy_channel (struct discord_channel *ch)
Destroys the given structure and frees the pointer.
void * disco_create_channel_mention_struct_json (cJSON *data)
Creates a channel_mention structure from a given JSON.
void disco_destroy_channel_mention (struct discord_channel_mention *ch)
Destroys the given structure and frees the pointer.
Enumeration Type Documentation
Discord_Channel_Type
enum Discord_Channel_Type
Enumerator
CHANNEL_GUILD_TEXT
CHANNEL_DM
CHANNEL_GROUP_DM
CHANNEL_GUILD_VOICE
CHANNEL_GUILD_CATEGORY
CHANNEL_GUILD_NEWS
CHANNEL_GUILD_NEWS_THREAD
CHANNEL_GUILD_PUBLIC_THREAD
CHANNEL_GUILD_PRIVATE_THREAD
CHANNEL_GUILD_STAGE_VOICE
CHANNEL_GUILD_DIRECTORY
CHANNEL_GUILD_FORUM
Function Documentation
disco_create_channel_mention_struct_json()
void* disco_create_channel_mention_struct_json (cJSON * data)
Creates a channel_mention structure from a given JSON.
Parameters
data
Returns
void* discord_channel_mention struct
References get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_channel_mention::guild_id, discord_channel_mention::id, discord_channel_mention::name, and discord_channel_mention::type.
Referenced by disco_create_message_struct_json().
disco_create_channel_struct_json()
void* disco_create_channel_struct_json (cJSON * data)
Creates a channel structure from a given JSON.
Parameters
data
Returns
void* discord_channel struct
References discord_channel::application_id, discord_channel::bitrate, discord_channel::default_auto_archive_duration, disco_create_overwrite_struct_json(), disco_create_thread_member_struct_json(), disco_create_thread_metadata_struct_json(), disco_create_user_struct_json(), discord_channel::flags, get_array_from_json(), get_bool_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_channel::guild_id, discord_channel::icon, discord_channel::id, discord_channel::last_message_id, discord_channel::last_pin_timestamp, discord_channel::member, discord_channel::member_count, discord_channel::message_count, discord_channel::name, discord_channel::nsfw, discord_channel::owner_id, discord_channel::parent_id, discord_channel::permission_overwrites, discord_channel::permission_overwrites_count, discord_channel::permissions, discord_channel::position, discord_channel::rate_limit_per_user, discord_channel::recipients, discord_channel::recipients_count, discord_channel::rtc_region, discord_channel::thread_metadata, discord_channel::topic, discord_channel::type, discord_channel::user_limit, and discord_channel::video_quality_mode.
Referenced by event_handle().
disco_destroy_channel()
void disco_destroy_channel (struct discord_channel * ch)
Destroys the given structure and frees the pointer.
Parameters
ch channel struct
References disco_destroy_overwrite(), disco_destroy_user(), discord_channel::icon, discord_channel::last_pin_timestamp, discord_channel::member, discord_channel::name, discord_channel::permission_overwrites, discord_channel::permission_overwrites_count, discord_channel::permissions, discord_channel::recipients, discord_channel::recipients_count, discord_channel::rtc_region, discord_channel::thread_metadata, and discord_channel::topic.
Referenced by default_destroy_callback(), and disco_destroy_message().
disco_destroy_channel_mention()
void disco_destroy_channel_mention (struct discord_channel_mention * ch)
Destroys the given structure and frees the pointer.
Parameters
ch channel_mention struct
References discord_channel_mention::name.