Disco-C: src/discord/command.c File Reference
command.c File Reference
#include "structures/command.h"
#include "../../config.h"
#include "../utils/disco_logging.h"
#include "../web/request.h"
#include <cJSON/cJSON.h>
#include <stdio.h>
#include <stdlib.h>
Functions
void discord_fill_json_with_locales (cJSON *json, struct discord_language_locales *locales)
Fills a JSON with the values of a langauge locales struct.
static void add_choice (cJSON *json, struct discord_application_command_option_choice *choice, enum Discord_Application_Command_Option_Type type)
static void add_option (cJSON *json, struct discord_application_command_option *option)
static int format_json (cJSON *json, struct discord_application_command *command)
int discord_command_register (struct discord_application_command *command)
int discord_command_update (struct discord_application_command *command, int64_t command_id)
int discord_command_delete_global (int64_t command_id)
int discord_command_delete_guild (int64_t guild_id, int64_t command_id)
Function Documentation
add_choice()
static void add_choice (cJSON * json, struct discord_application_command_option_choice * choice, enum Discord_Application_Command_Option_Type type) static
References COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, discord_fill_json_with_locales(), discord_application_command_option_choice::name, discord_application_command_option_choice::name_localizations, discord_application_command_option_choice::number, discord_channel_mention::type, and discord_application_command_option_choice::value.
Referenced by add_option().
add_option()
static void add_option (cJSON * json, struct discord_application_command_option * option) static
References add_choice(), discord_application_command_option::autocomplete, discord_application_command_option::channel_types, discord_application_command_option::channel_types_count, discord_application_command_option::choices, discord_application_command_option::choices_count, COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, COMMAND_OPTION_STRING, discord_application_command_option::description, discord_application_command_option::description_localizations, discord_fill_json_with_locales(), discord_application_command_option::max_length, discord_application_command_option::max_value, discord_application_command_option::min_length, discord_application_command_option::min_value, discord_application_command_option::name, discord_application_command_option::name_localizations, discord_application_command_option::options, discord_application_command_option::options_count, discord_application_command_option::required, and discord_application_command_option::type.
Referenced by format_json().
discord_command_delete_global()
int discord_command_delete_global (int64_t command_id)
References request(), and REQUEST_DELETE.
discord_command_delete_guild()
int discord_command_delete_guild (int64_t guild_id, int64_t command_id)
References request(), and REQUEST_DELETE.
discord_command_register()
int discord_command_register (struct discord_application_command * command)
References d_log_notice, format_json(), discord_application_command::guild_id, request(), and REQUEST_POST.
discord_command_update()
int discord_command_update (struct discord_application_command * command, int64_t command_id)
References format_json(), discord_application_command::guild_id, request(), and REQUEST_PATCH.
discord_fill_json_with_locales()
void discord_fill_json_with_locales (cJSON * json, struct discord_language_locales * locales)
Fills a JSON with the values of a langauge locales struct.
Parameters
json JSON struct to fill the values in.
locales struct to be used to fill in the JSON.
References discord_language_locales::bg, discord_language_locales::cs, discord_language_locales::da, discord_language_locales::de, discord_language_locales::el, discord_language_locales::en_GB, discord_language_locales::en_US, discord_language_locales::es_ES, discord_language_locales::fi, discord_language_locales::fr, discord_language_locales::hi, discord_language_locales::hr, discord_language_locales::hu, discord_language_locales::it, discord_language_locales::ja, discord_language_locales::ko, discord_language_locales::lt, discord_language_locales::nl, discord_language_locales::no, discord_language_locales::pl, discord_language_locales::pt_BR, discord_language_locales::ro, discord_language_locales::ru, discord_language_locales::sv_SE, discord_language_locales::th, discord_language_locales::tr, discord_language_locales::uk, discord_language_locales::vi, discord_language_locales::zh_CN, and discord_language_locales::zh_TW.
Referenced by add_choice(), add_option(), disco_send_interaction(), and format_json().
format_json()
static int format_json (cJSON * json, struct discord_application_command * command) static
References add_option(), d_log_err, discord_application_command::default_member_permissions, discord_application_command::description, discord_application_command::description_localizations, discord_fill_json_with_locales(), discord_application_command::dm_permission, discord_application_command::name, discord_application_command::name_localizations, discord_application_command::options, discord_application_command::options_count, discord_application_command_option::required, discord_application_command::type, and discord_application_command::version.
Referenced by discord_command_register(), and discord_command_update().