Disco-C: src/discord/component.c File Reference
component.c File Reference
#include "structures/component.h"
#include "disco.h"
#include "structures/emoji.h"
Functions
void * disco_create_component_struct_json (cJSON *data)
Creates a component structure from a given JSON with the correct type.
void disco_destroy_component (struct discord_component *c)
Destroys the given structure and frees the pointer.
void * disco_create_select_option_struct (cJSON *data)
Creates a select option structure from a given JSON.
void disco_destroy_select_option (struct discord_select_option *option)
Destroys the given structure and frees the pointer.
void discord_fill_json_with_component (cJSON *json, struct discord_component *c)
Fills in a JSON with the attributes of the component structure.
Function Documentation
disco_create_component_struct_json()
void* disco_create_component_struct_json (cJSON * data)
Creates a component structure from a given JSON with the correct type.
Parameters
data
Returns
void* discord_component struct
References discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, discord_button::disabled, discord_select_menu::disabled, disco_create_component_struct_json(), disco_create_emoji_struct_json(), disco_create_select_option_struct(), discord_button::emoji, get_array_from_json(), get_bool_from_json(), get_int_from_json(), get_string_from_json(), discord_button::label, discord_text_input::label, discord_text_input::max_length, discord_select_menu::max_values, discord_text_input::min_length, discord_select_menu::min_values, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_text_input::required, discord_component::select_menu, discord_button::style, discord_text_input::style, discord_component::text_input, discord_button::url, and discord_text_input::value.
Referenced by disco_create_component_struct_json(), disco_create_interaction_data_struct_json(), and disco_create_message_struct_json().
disco_create_select_option_struct()
void* disco_create_select_option_struct (cJSON * data)
Creates a select option structure from a given JSON.
Parameters
data
Returns
void* discord_select_option struct
References discord_select_option::_default, discord_select_option::description, disco_create_emoji_struct_json(), discord_select_option::emoji, get_bool_from_json(), get_string_from_json(), discord_select_option::label, and discord_select_option::value.
Referenced by disco_create_component_struct_json(), and disco_create_interaction_data_struct_json().
disco_destroy_component()
void disco_destroy_component (struct discord_component * c)
Destroys the given structure and frees the pointer.
Parameters
c discord_component struct
References discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, disco_destroy_component(), disco_destroy_emoji(), disco_destroy_select_option(), discord_button::emoji, discord_button::label, discord_text_input::label, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_component::select_menu, discord_component::text_input, discord_component::type, discord_button::url, and discord_text_input::value.
Referenced by disco_destroy_component(), disco_destroy_interaction_data(), and disco_destroy_message().
disco_destroy_select_option()
void disco_destroy_select_option (struct discord_select_option * option)
Destroys the given structure and frees the pointer.
Parameters
option
References discord_select_option::description, disco_destroy_emoji(), discord_select_option::emoji, discord_select_option::label, and discord_select_option::value.
Referenced by disco_destroy_component().
discord_fill_json_with_component()
void discord_fill_json_with_component (cJSON * json, struct discord_component * component)
Fills in a JSON with the attributes of the component structure.
Parameters
json JSON struct that should be filled in with the values.
component The component that will be used to fill the JSON.
Referenced by disco_send_interaction().