Disco-C: src/discord/structures/component.h File Reference
component.h File Reference
#include "emoji.h"
#include "user.h"
#include <cJSON/cJSON.h>
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_action_row
struct discord_button
struct discord_select_option
struct discord_select_menu
struct discord_text_input
struct discord_component
Enumerations
enum Discord_Component_Type { COMPONENT_ACTION_ROW = 1, COMPONENT_BUTTON = 2, COMPONENT_SELECT_MENU = 3, COMPONENT_TEXT_INPUT = 4 }
enum Discord_Button_Style {
BUTTON_PRIMARY = 1, BUTTON_SECONDARY = 2, BUTTON_SUCCESS = 3, BUTTON_DANGER = 4,
BUTTON_LINK = 5
}
enum Discord_Text_Input_Style { TEXT_INPUT_SHORT = 1, TEXT_INPUT_PARAGRAPH = 2 }
Functions
void * disco_create_select_option_struct (cJSON *data)
Creates a select option structure from a given JSON.
void disco_destroy_select_option (struct discord_select_option *option)
Destroys the given structure and frees the pointer.
void * disco_create_component_struct_json (cJSON *data)
Creates a component structure from a given JSON with the correct type.
void disco_destroy_component (struct discord_component *c)
Destroys the given structure and frees the pointer.
void discord_fill_json_with_component (cJSON *json, struct discord_component *component)
Fills in a JSON with the attributes of the component structure.
Enumeration Type Documentation
Discord_Button_Style
enum Discord_Button_Style
Enumerator
BUTTON_PRIMARY
BUTTON_SECONDARY
BUTTON_SUCCESS
BUTTON_DANGER
BUTTON_LINK
Discord_Component_Type
enum Discord_Component_Type
Enumerator
COMPONENT_ACTION_ROW
COMPONENT_BUTTON
COMPONENT_SELECT_MENU
COMPONENT_TEXT_INPUT
Discord_Text_Input_Style
enum Discord_Text_Input_Style
Enumerator
TEXT_INPUT_SHORT
TEXT_INPUT_PARAGRAPH
Function Documentation
disco_create_component_struct_json()
void* disco_create_component_struct_json (cJSON * data)
Creates a component structure from a given JSON with the correct type.
Parameters
data
Returns
void* discord_component struct
References discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, discord_button::disabled, discord_select_menu::disabled, disco_create_component_struct_json(), disco_create_emoji_struct_json(), disco_create_select_option_struct(), discord_button::emoji, get_array_from_json(), get_bool_from_json(), get_int_from_json(), get_string_from_json(), discord_button::label, discord_text_input::label, discord_text_input::max_length, discord_select_menu::max_values, discord_text_input::min_length, discord_select_menu::min_values, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_text_input::required, discord_component::select_menu, discord_button::style, discord_text_input::style, discord_component::text_input, discord_button::url, and discord_text_input::value.
Referenced by disco_create_component_struct_json(), disco_create_interaction_data_struct_json(), and disco_create_message_struct_json().
disco_create_select_option_struct()
void* disco_create_select_option_struct (cJSON * data)
Creates a select option structure from a given JSON.
Parameters
data
Returns
void* discord_select_option struct
References discord_select_option::_default, discord_select_option::description, disco_create_emoji_struct_json(), discord_select_option::emoji, get_bool_from_json(), get_string_from_json(), discord_select_option::label, and discord_select_option::value.
Referenced by disco_create_component_struct_json(), and disco_create_interaction_data_struct_json().
disco_destroy_component()
void disco_destroy_component (struct discord_component * c)
Destroys the given structure and frees the pointer.
Parameters
c discord_component struct
References discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, disco_destroy_component(), disco_destroy_emoji(), disco_destroy_select_option(), discord_button::emoji, discord_button::label, discord_text_input::label, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_component::select_menu, discord_component::text_input, discord_component::type, discord_button::url, and discord_text_input::value.
Referenced by disco_destroy_component(), disco_destroy_interaction_data(), and disco_destroy_message().
disco_destroy_select_option()
void disco_destroy_select_option (struct discord_select_option * option)
Destroys the given structure and frees the pointer.
Parameters
option
References discord_select_option::description, disco_destroy_emoji(), discord_select_option::emoji, discord_select_option::label, and discord_select_option::value.
Referenced by disco_destroy_component().
discord_fill_json_with_component()
void discord_fill_json_with_component (cJSON * json, struct discord_component * component)
Fills in a JSON with the attributes of the component structure.
Parameters
json JSON struct that should be filled in with the values.
component The component that will be used to fill the JSON.
Referenced by disco_send_interaction().