Disco-C: src/discord/disco.c File Reference
disco.c File Reference
#include <cJSON/cJSON.h>
#include <curl/curl.h>
#include <discord/disco.h>
#include <stdlib.h>
#include <string.h>
#include <utils/cache.h>
#include <utils/disco_logging.h>
#include <web/gateway.h>
#include <web/request.h>
Functions
void discord_start_bot (discord_event_callbacks_t *callbacks)
High level abstraction which starts the bot.
char * get_string_from_json (cJSON *data, const char *name)
bool get_bool_from_json (cJSON *data, const char *name, int default_)
Get a bool from json object.
int get_int_from_json (cJSON *data, const char *name, int default_)
Get an int from json object.
int get_array_from_json (cJSON *data, const char *name, void ***array, size_t s, discord_struct_fn func)
uint64_t get_long_from_string_json (cJSON *data, const char *name, uint64_t default_)
double get_double_from_string_json (cJSON *data, const char *name, double default_)
Function Documentation
get_array_from_json()
int get_array_from_json (cJSON * data, const char * name, void *** array, size_t s, discord_struct_fn func)
References s.
Referenced by discord_create_channel_struct_json(), discord_create_component_struct_json(), discord_create_embed_struct_json(), discord_create_interaction_data_option_struct_json(), discord_create_interaction_data_struct_json(), and discord_create_message_struct_json().
get_bool_from_json()
bool get_bool_from_json (cJSON * data, const char * name, int default_)
Get a bool from json object.
Parameters
data
name
default_ The default value incase the field doesn't exist
Returns
int
Referenced by discord_create_attachment_struct_json(), discord_create_channel_struct_json(), discord_create_component_struct_json(), discord_create_embed_field_struct_json(), discord_create_interaction_data_option_struct_json(), discord_create_message_struct_json(), discord_create_select_option_struct(), discord_create_user_struct_json(), and test_message_creation().
get_double_from_string_json()
double get_double_from_string_json (cJSON * data, const char * name, double default_)
Referenced by discord_create_interaction_data_option_struct_json().
get_int_from_json()
int get_int_from_json (cJSON * data, const char * name, int default_)
Get an int from json object.
Parameters
data
name
default_ The default value incase the field doesn't exist
Returns
bool
Referenced by discord_create_attachment_struct_json(), discord_create_channel_mention_struct_json(), discord_create_channel_struct_json(), discord_create_component_struct_json(), discord_create_embed_media_struct_json(), discord_create_embed_struct_json(), discord_create_interaction_data_option_struct_json(), discord_create_interaction_data_struct_json(), discord_create_interaction_struct_json(), discord_create_message_struct_json(), and discord_create_user_struct_json().
get_long_from_string_json()
uint64_t get_long_from_string_json (cJSON * data, const char * name, uint64_t default_)
Referenced by discord_create_attachment_struct_json(), discord_create_channel_mention_struct_json(), discord_create_channel_struct_json(), discord_create_interaction_data_struct_json(), discord_create_interaction_struct_json(), discord_create_message_reference_struct_json(), discord_create_message_struct_json(), and discord_create_user_struct_json().
get_string_from_json()
char* get_string_from_json (cJSON * data, const char * name)
Referenced by discord_create_attachment_struct_json(), discord_create_channel_mention_struct_json(), discord_create_channel_struct_json(), discord_create_component_struct_json(), discord_create_embed_author_struct_json(), discord_create_embed_field_struct_json(), discord_create_embed_footer_struct_json(), discord_create_embed_media_struct_json(), discord_create_embed_provider_struct_json(), discord_create_embed_struct_json(), discord_create_interaction_data_option_struct_json(), discord_create_interaction_data_struct_json(), discord_create_interaction_struct_json(), discord_create_message_struct_json(), discord_create_select_option_struct(), and discord_create_user_struct_json().