Disco-C: src/discord/disco.h File Reference
disco.h File Reference
#include "../utils/t_pool.h"
#include "../web/websocket.h"
#include "structures/application.h"
#include "structures/attachment.h"
#include "structures/channel.h"
#include "structures/component.h"
#include "structures/guild.h"
#include "structures/interaction.h"
#include "structures/message.h"
#include "structures/message_activity.h"
#include "structures/permission.h"
#include "structures/reaction.h"
#include "structures/role.h"
#include "structures/sticker.h"
#include "structures/thread.h"
#include "structures/user.h"
#include <cJSON/cJSON.h>
#include <stdbool.h>
#include <stdint.h>
Classes
struct disco_event_callbacks
struct bot_client
Typedefs
typedef struct websocket_client websocket_client_t
typedef struct bot_client bot_client_t
typedef struct disco_event_callbacks disco_event_callbacks_t
typedef void *(* disco_struct_fn) (cJSON *)
Functions
void disco_start_bot (disco_event_callbacks_t *callbacks)
High level abstraction which starts the bot.
void disco_free_bot (bot_client_t *bot)
Frees up memory for a bot instance.
char * get_string_from_json (cJSON *data, const char *name)
bool get_bool_from_json (cJSON *data, const char *name, int default_)
Get a bool from json object.
int get_int_from_json (cJSON *data, const char *name, int default_)
Get an int from json object.
int get_array_from_json (cJSON *data, const char *name, void ***array, size_t s, disco_struct_fn func)
uint64_t get_long_from_string_json (cJSON *data, const char *name, uint64_t default_)
double get_double_from_string_json (cJSON *data, const char *name, double default_)
Typedef Documentation
bot_client_t
typedef struct bot_client bot_client_t
disco_event_callbacks_t
typedef struct disco_event_callbacks disco_event_callbacks_t
disco_struct_fn
typedef void*(* disco_struct_fn) (cJSON *)
websocket_client_t
typedef struct websocket_client websocket_client_t
Function Documentation
disco_free_bot()
void disco_free_bot (bot_client_t * bot)
Frees up memory for a bot instance.
Parameters
bot Bot instance
disco_start_bot()
void disco_start_bot (disco_event_callbacks_t * callbacks)
High level abstraction which starts the bot.
Parameters
callbacks A callbacks object containing the callbacks to the event functions.
References bot, bot_client::callbacks, client, d_log_err, disco_cache_destroy(), disco_cache_init(), disco_destroy_user(), gateway_event_loop(), gateway_on_receive(), t_pool_destroy(), t_pool_init(), t_process_count(), bot_client::thread_pool, bot_client::user, bot_client::websocket_client, websocket_connect(), websocket_create(), and websocket_destroy_client().
Referenced by main().
get_array_from_json()
int get_array_from_json (cJSON * data, const char * name, void *** array, size_t s, disco_struct_fn func)
References s.
Referenced by disco_create_channel_struct_json(), disco_create_component_struct_json(), disco_create_embed_struct_json(), disco_create_interaction_data_option_struct_json(), disco_create_interaction_data_struct_json(), and disco_create_message_struct_json().
get_bool_from_json()
bool get_bool_from_json (cJSON * data, const char * name, int default_)
Get a bool from json object.
Parameters
data
name
default_ The default value incase the field doesn't exist
Returns
int
Referenced by disco_create_attachment_struct_json(), disco_create_channel_struct_json(), disco_create_component_struct_json(), disco_create_embed_field_struct_json(), disco_create_interaction_data_option_struct_json(), disco_create_message_struct_json(), disco_create_select_option_struct(), disco_create_user_struct_json(), and test_message_creation().
get_double_from_string_json()
double get_double_from_string_json (cJSON * data, const char * name, double default_)
Referenced by disco_create_interaction_data_option_struct_json().
get_int_from_json()
int get_int_from_json (cJSON * data, const char * name, int default_)
Get an int from json object.
Parameters
data
name
default_ The default value incase the field doesn't exist
Returns
bool
Referenced by disco_create_attachment_struct_json(), disco_create_channel_mention_struct_json(), disco_create_channel_struct_json(), disco_create_component_struct_json(), disco_create_embed_media_struct_json(), disco_create_embed_struct_json(), disco_create_interaction_data_option_struct_json(), disco_create_interaction_data_struct_json(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), and disco_create_user_struct_json().
get_long_from_string_json()
uint64_t get_long_from_string_json (cJSON * data, const char * name, uint64_t default_)
Referenced by disco_create_attachment_struct_json(), disco_create_channel_mention_struct_json(), disco_create_channel_struct_json(), disco_create_interaction_data_struct_json(), disco_create_interaction_struct_json(), disco_create_message_reference_struct_json(), disco_create_message_struct_json(), and disco_create_user_struct_json().
get_string_from_json()
char* get_string_from_json (cJSON * data, const char * name)
Referenced by disco_create_attachment_struct_json(), disco_create_channel_mention_struct_json(), disco_create_channel_struct_json(), disco_create_component_struct_json(), disco_create_embed_author_struct_json(), disco_create_embed_field_struct_json(), disco_create_embed_footer_struct_json(), disco_create_embed_media_struct_json(), disco_create_embed_provider_struct_json(), disco_create_embed_struct_json(), disco_create_interaction_data_option_struct_json(), disco_create_interaction_data_struct_json(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), disco_create_select_option_struct(), and disco_create_user_struct_json().