Disco-C: src/discord/structures/embed.h File Reference
embed.h File Reference
#include <cJSON/cJSON.h>
#include <stdbool.h>
Classes
struct discord_embed_footer
struct discord_embed_media
struct discord_embed_provider
struct discord_embed_author
struct discord_embed_field
struct discord_embed
Functions
void * disco_create_embed_footer_struct_json (cJSON *data)
Creates an embed_footer structure from a given JSON.
void disco_destroy_embed_footer (struct discord_embed_footer *footer)
Destroys the given structure and frees the pointer.
void * disco_create_embed_media_struct_json (cJSON *data)
Creates an embed_media structure from a given JSON.
void disco_destroy_embed_media (struct discord_embed_media *media)
Destroys the given structure and frees the pointer.
void * disco_create_embed_provider_struct_json (cJSON *data)
Creates an embed_provider structure from a given JSON.
void disco_destroy_embed_provider (struct discord_embed_provider *provider)
Destroys the given structure and frees the pointer.
void * disco_create_embed_author_struct_json (cJSON *data)
Creates an embed_author structure from a given JSON.
void disco_destroy_embed_author (struct discord_embed_author *author)
Destroys the given structure and frees the pointer.
void * disco_create_embed_field_struct_json (cJSON *data)
Creates an embed_field structure from a given JSON.
void disco_destroy_embed_field (struct discord_embed_field *field)
Destroys the given structure and frees the pointer.
void * disco_create_embed_struct_json (cJSON *data)
Creates an embed structure from a given JSON.
void disco_destroy_embed (struct discord_embed *embed)
Destroys the given structure and frees the pointer.
Function Documentation
disco_create_embed_author_struct_json()
void* disco_create_embed_author_struct_json (cJSON * data)
Creates an embed_author structure from a given JSON.
Parameters
data
Returns
void* discord_embed_author struct
References get_string_from_json(), discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by disco_create_embed_struct_json().
disco_create_embed_field_struct_json()
void* disco_create_embed_field_struct_json (cJSON * data)
Creates an embed_field structure from a given JSON.
Parameters
data
Returns
void* discord_embed_field struct
References discord_embed_field::_inline, get_bool_from_json(), get_string_from_json(), discord_embed_field::name, and discord_embed_field::value.
Referenced by disco_create_embed_struct_json().
disco_create_embed_footer_struct_json()
void* disco_create_embed_footer_struct_json (cJSON * data)
Creates an embed_footer structure from a given JSON.
Parameters
data
Returns
void* discord_embed_footer struct
References get_string_from_json(), discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
Referenced by disco_create_embed_struct_json().
disco_create_embed_media_struct_json()
void* disco_create_embed_media_struct_json (cJSON * data)
Creates an embed_media structure from a given JSON.
Parameters
data
Returns
void* discord_embed_media struct
References get_int_from_json(), get_string_from_json(), discord_embed_media::height, discord_embed_media::proxy_url, discord_embed_media::url, and discord_embed_media::width.
Referenced by disco_create_embed_struct_json().
disco_create_embed_provider_struct_json()
void* disco_create_embed_provider_struct_json (cJSON * data)
Creates an embed_provider structure from a given JSON.
Parameters
data
Returns
void* discord_embed_provider struct
References get_string_from_json(), discord_embed_provider::name, and discord_embed_provider::url.
Referenced by disco_create_embed_struct_json().
disco_create_embed_struct_json()
void* disco_create_embed_struct_json (cJSON * data)
Creates an embed structure from a given JSON.
Parameters
data
Returns
void* discord_embed struct
References discord_embed::author, discord_embed::color, discord_embed::description, disco_create_embed_author_struct_json(), disco_create_embed_field_struct_json(), disco_create_embed_footer_struct_json(), disco_create_embed_media_struct_json(), disco_create_embed_provider_struct_json(), discord_embed::fields, discord_embed::fields_count, discord_embed::footer, get_array_from_json(), get_int_from_json(), get_string_from_json(), discord_embed::image, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed::url, and discord_embed::video.
disco_destroy_embed()
void disco_destroy_embed (struct discord_embed * embed)
Destroys the given structure and frees the pointer.
Parameters
embed
References discord_embed::author, discord_embed::description, disco_destroy_embed_author(), disco_destroy_embed_field(), disco_destroy_embed_footer(), disco_destroy_embed_media(), disco_destroy_embed_provider(), discord_embed::fields, discord_embed::fields_count, discord_embed::footer, discord_embed::image, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed::url, and discord_embed::video.
Referenced by disco_destroy_message().
disco_destroy_embed_author()
void disco_destroy_embed_author (struct discord_embed_author * author)
Destroys the given structure and frees the pointer.
Parameters
author
References discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by disco_destroy_embed().
disco_destroy_embed_field()
void disco_destroy_embed_field (struct discord_embed_field * field)
Destroys the given structure and frees the pointer.
Parameters
field
References discord_embed_field::name, and discord_embed_field::value.
Referenced by disco_destroy_embed().
disco_destroy_embed_footer()
void disco_destroy_embed_footer (struct discord_embed_footer * footer)
Destroys the given structure and frees the pointer.
Parameters
footer
References discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
Referenced by disco_destroy_embed().
disco_destroy_embed_media()
void disco_destroy_embed_media (struct discord_embed_media * media)
Destroys the given structure and frees the pointer.
Parameters
media
References discord_embed_media::proxy_url, and discord_embed_media::url.
Referenced by disco_destroy_embed().
disco_destroy_embed_provider()
void disco_destroy_embed_provider (struct discord_embed_provider * provider)
Destroys the given structure and frees the pointer.
Parameters
provider
References discord_embed_provider::name, and discord_embed_provider::url.
Referenced by disco_destroy_embed().