Disco-C: src/discord/structures/emoji.h File Reference
emoji.h File Reference
#include "user.h"
#include <cJSON/cJSON.h>
#include <stdbool.h>
Classes
struct discord_emoji
Functions
void * disco_create_emoji_struct_json (cJSON *data)
void disco_destroy_emoji (struct discord_emoji *emoji)
Function Documentation
disco_create_emoji_struct_json()
void* disco_create_emoji_struct_json (cJSON * data)
Referenced by disco_create_component_struct_json(), and disco_create_select_option_struct().
disco_destroy_emoji()
void disco_destroy_emoji (struct discord_emoji * emoji)
Referenced by disco_destroy_component(), and disco_destroy_select_option().