Disco-C: src/discord/event.h File Reference
event.h File Reference
#include "disco.h"
#include <cJSON/cJSON.h>
Classes
struct event_pool_workload
Typedefs
typedef struct event_pool_workload event_pool_workload_t
Functions
void event_handle (bot_client_t *bot_client, cJSON *data, char *event)
All event websocket responses call this function.
Typedef Documentation
event_pool_workload_t
typedef struct event_pool_workload event_pool_workload_t
Function Documentation
event_handle()
void event_handle (bot_client_t * bot_client, cJSON * data, char * event)
All event websocket responses call this function.
Parameters
bot_client Active bot instance
data The received data in a JSON struct
event The event that was called as a string
References bot, event_pool_workload::bot, bot_client::callbacks, delete_channel::channel, delete_message::channel_id, d_log_debug, d_log_err, d_log_normal, event_pool_workload::data, discord_interaction::data, disco_cache_get_channel(), disco_cache_get_message(), disco_cache_set_channel(), disco_cache_set_message(), disco_create_channel_struct_json(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), disco_create_user_struct_json(), disco_destroy_user(), event_handle_channel_create(), event_handle_channel_delete(), event_handle_channel_update(), event_handle_interaction_create(), event_handle_message_create(), event_handle_message_delete(), event_handle_message_update(), event_handle_ready(), delete_message::guild_id, delete_channel::guild_id, discord_channel::id, delete_message::id, delete_channel::id, discord_message::id, delete_message::message, edit_message::new, edit_channel::new, edit_message::old, edit_channel::old, disco_event_callbacks::on_channel_create, disco_event_callbacks::on_channel_delete, disco_event_callbacks::on_channel_update, disco_event_callbacks::on_interaction, disco_event_callbacks::on_message, disco_event_callbacks::on_message_delete, disco_event_callbacks::on_message_edit, disco_event_callbacks::on_ready, delete_channel::parent_id, t_pool_add_work(), bot_client::thread_pool, delete_channel::type, and bot_client::user.
Referenced by gateway_handle_dispatch().