Disco-C: src/discord/event.c File Reference
event.c File Reference
#include <discord/event.h>
#include <discord/user.h>
#include <string.h>
#include <utils/cache.h>
#include <utils/disco_logging.h>
#include <utils/t_pool.h>
#include <utils/timer.h>
#include <web/websocket.h>
Data Structures
struct edit_message
struct delete_message
struct edit_channel
struct delete_channel
Functions
void event_handle_ready (void *b)
void event_handle_message_create (void *w)
void event_handle_message_update (void *w)
void event_handle_message_delete (void *w)
void event_handle_channel_create (void *w)
void event_handle_channel_update (void *w)
void event_handle_channel_delete (void *w)
void event_handle_interaction_create (void *w)
void event_handle (bot_client_t *bot, cJSON *data, char *event)
All event websocket responses call this function.
Function Documentation
event_handle()
void event_handle (bot_client_t * bot_client, cJSON * data, char * event)
All event websocket responses call this function.
Parameters
bot_client Active bot instance
data The received data in a JSON struct
event The event that was called as a string
References _d_copy_channel(), _d_copy_message(), _d_json_to_channel(), _d_json_to_interaction(), _d_json_to_message(), _d_json_to_user(), event_pool_workload::bot, discord_user::bot, bot_client::callbacks, delete_channel::channel, delete_message::channel_id, d_log_debug, d_log_err, d_log_normal, d_log_notice, event_pool_workload::data, discord_interaction::data, discord_cache_get_channel(), discord_cache_get_message(), discord_cache_set_channel(), discord_cache_set_message(), discord_destroy_user(), event_handle_channel_create(), event_handle_channel_delete(), event_handle_channel_update(), event_handle_interaction_create(), event_handle_message_create(), event_handle_message_delete(), event_handle_message_update(), event_handle_ready(), delete_message::guild_id, delete_channel::guild_id, discord_channel::id, delete_message::id, delete_channel::id, discord_message::id, delete_message::message, edit_message::new, edit_channel::new, edit_message::old, edit_channel::old, discord_event_callbacks::on_channel_delete, discord_event_callbacks::on_channel_update, discord_event_callbacks::on_interaction_create, discord_event_callbacks::on_message, discord_event_callbacks::on_message_delete, discord_event_callbacks::on_message_edit, delete_channel::parent_id, t_pool_add_work(), bot_client::thread_pool, delete_channel::type, and bot_client::user.
Referenced by gateway_handle_dispatch().
event_handle_channel_create()
void event_handle_channel_create (void * w)
References event_pool_workload::bot, bot_client::callbacks, event_pool_workload::data, and discord_event_callbacks::on_channel_create.
Referenced by event_handle().
event_handle_channel_delete()
void event_handle_channel_delete (void * w)
References event_pool_workload::bot, bot_client::callbacks, delete_channel::channel, d_log_debug, d_log_notice, event_pool_workload::data, delete_channel::guild_id, delete_channel::id, discord_event_callbacks::on_channel_delete, delete_channel::parent_id, and delete_channel::type.
Referenced by event_handle().
event_handle_channel_update()
void event_handle_channel_update (void * w)
References event_pool_workload::bot, bot_client::callbacks, event_pool_workload::data, edit_channel::new, edit_channel::old, and discord_event_callbacks::on_channel_update.
Referenced by event_handle().
event_handle_interaction_create()
void event_handle_interaction_create (void * w)
References event_pool_workload::bot, bot_client::callbacks, event_pool_workload::data, and discord_event_callbacks::on_interaction_create.
Referenced by event_handle().
event_handle_message_create()
void event_handle_message_create (void * w)
References event_pool_workload::bot, bot_client::callbacks, event_pool_workload::data, and discord_event_callbacks::on_message.
Referenced by event_handle().
event_handle_message_delete()
void event_handle_message_delete (void * w)
References event_pool_workload::bot, bot_client::callbacks, delete_message::channel_id, d_log_debug, d_log_notice, event_pool_workload::data, delete_message::guild_id, delete_message::id, delete_message::message, and discord_event_callbacks::on_message_delete.
Referenced by event_handle().
event_handle_message_update()
void event_handle_message_update (void * w)
References event_pool_workload::bot, bot_client::callbacks, event_pool_workload::data, edit_message::new, edit_message::old, and discord_event_callbacks::on_message_edit.
Referenced by event_handle().
event_handle_ready()
void event_handle_ready (void * b)
References bot_client::callbacks, and discord_event_callbacks::on_ready.
Referenced by event_handle().