Disco-C: example/example_slash_commands/example_slash.h File Reference
example_slash.h File Reference
Functions
void hello_callback (struct discord_interaction *interaction)
int register_hello_command (void)
Function Documentation
hello_callback()
void hello_callback (struct discord_interaction * interaction)
References disco_send_interaction(), DISCORD_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE, and discord_interaction_callback::type.
Referenced by example_interaction_create().
register_hello_command()
int register_hello_command (void)
References COMMAND_CHAT_INPUT, discord_application_command::description, discord_command_register(), discord_application_command::guild_id, discord_application_command::name, and discord_application_command::type.
Referenced by main().