Disco-C: example/example.c File Reference
example.c File Reference
#include "example.h"
#include "../src/utils/disco_logging.h"
#include "example_slash_commands/example_slash.h"
#include "sys/time.h"
#include <stdbool.h>
Functions
void example_on_ready (bot_client_t *bot)
void example_on_message (bot_client_t *bot, struct discord_message *message)
void example_on_edit (bot_client_t *bot, struct discord_message *old, struct discord_message *new)
void example_on_delete (bot_client_t *bot, uint64_t message_id, uint64_t channel_id, uint64_t guild_id, struct discord_message *message)
void example_channel_create (bot_client_t *bot, struct discord_channel *channel)
void example_channel_update (bot_client_t *bot, struct discord_channel *old, struct discord_channel *new)
void example_channel_delete (bot_client_t *bot, uint64_t channel_id, uint64_t guild_id, uint64_t parent_id, enum Discord_Channel_Type type, struct discord_channel *channel)
void example_interaction_create (bot_client_t *bot, struct discord_interaction *interaction)
Function Documentation
example_channel_create()
void example_channel_create (bot_client_t * bot, struct discord_channel * channel)
References bot, d_log_normal, and discord_channel::id.
Referenced by main().
example_channel_delete()
void example_channel_delete (bot_client_t * bot, uint64_t channel_id, uint64_t guild_id, uint64_t parent_id, enum Discord_Channel_Type type, struct discord_channel * channel)
References bot, discord_message::channel_id, d_log_normal, discord_message::guild_id, discord_channel::id, and discord_message::type.
Referenced by main().
example_channel_update()
void example_channel_update (bot_client_t * bot, struct discord_channel * old, struct discord_channel * new)
References bot, d_log_normal, and discord_channel::id.
Referenced by main().
example_interaction_create()
void example_interaction_create (bot_client_t * bot, struct discord_interaction * interaction)
References bot, discord_interaction::channel_id, discord_interaction_data::custom_id, d_log_notice, discord_interaction::data, disco_destroy_interaction(), discord_interaction::guild_id, hello_callback(), discord_interaction::id, discord_interaction_data::name, and discord_interaction::type.
Referenced by main().
example_on_delete()
void example_on_delete (bot_client_t * bot, uint64_t message_id, uint64_t channel_id, uint64_t guild_id, struct discord_message * message)
References bot, discord_message::channel_id, discord_message::content, disco_channel_send_message(), and discord_message::guild_id.
Referenced by main().
example_on_edit()
void example_on_edit (bot_client_t * bot, struct discord_message * old, struct discord_message * new)
References bot, discord_message::content, disco_channel_send_message(), and discord_message::id.
Referenced by main().
example_on_message()
void example_on_message (bot_client_t * bot, struct discord_message * message)
References discord_message::author, bot, discord_user::bot, discord_message::channel_id, discord_message::content, discord_embed::description, disco_channel_edit_message(), disco_channel_send_message(), disco_destroy_message(), discord_create_message::embed, bot_client::heartbeat_latency, discord_message::id, websocket_close(), and websocket_reconnect().
Referenced by main().
example_on_ready()
void example_on_ready (bot_client_t * bot)
References bot, discord_user::id, bot_client::user, and discord_user::username.
Referenced by main().