Disco-C: src/web/gateway.c File Reference
gateway.c File Reference
#include "gateway.h"
#include "../../config.h"
#include "../discord/event.h"
#include "../utils/disco_logging.h"
#include "websocket.h"
#include <cJSON/cJSON.h>
#include <pthread.h>
#include <time.h>
#include <unistd.h>
Functions
static void gateway_handle_identify (websocket_client_t *client)
static void gateway_send_heartbeat (websocket_client_t *client)
static void gateway_handle_dispatch (bot_client_t *bot, cJSON *json)
void gateway_on_receive (bot_client_t *bot, char *data, size_t len)
Callback function for when a websocket package is received.
void * gateway_heartbeat_loop (void *vargp)
Initiates the heartbeat loop. Intended to be run on a seperate thread.
void gateway_event_loop (bot_client_t *bot)
Initiates the event loop. This is the main loop that needs to be run for the bot to work.
Variables
static int s = -1
static unsigned int HEARTBEAT_INTERVAL = 10000
static struct timeval last_hearbeat
Function Documentation
gateway_event_loop()
void gateway_event_loop (bot_client_t * bot)
Initiates the event loop. This is the main loop that needs to be run for the bot to work.
Parameters
bot Active bot instance
References websocket_client::active, bot, websocket_client::context, and bot_client::websocket_client.
Referenced by disco_start_bot().
gateway_handle_dispatch()
static void gateway_handle_dispatch (bot_client_t * bot, cJSON * json) static
References bot, event_handle(), and s.
Referenced by gateway_on_receive().
gateway_handle_identify()
static void gateway_handle_identify (websocket_client_t * client) static
References client, d_log_notice, gateway_heartbeat_loop(), websocket_client::heartbeat_active, websocket_client::heartbeat_thread, websocket_send(), and websocket_client::wsi.
Referenced by gateway_on_receive().
gateway_heartbeat_loop()
void* gateway_heartbeat_loop (void * vargp)
Initiates the heartbeat loop. Intended to be run on a seperate thread.
Parameters
vargp Pointer to the active websocket client
Returns
void*
References websocket_client::active, client, d_log_debug, gateway_send_heartbeat(), websocket_client::heartbeat_active, and HEARTBEAT_INTERVAL.
Referenced by gateway_handle_identify().
gateway_on_receive()
void gateway_on_receive (bot_client_t * bot_client, char * data, size_t len)
Callback function for when a websocket package is received.
Parameters
bot_client A bot instance
data The data that was received
len The length of the data
References bot, d_log_debug, d_log_err, d_log_notice, DISCORD_DISPATCH, DISCORD_HEARTBEAT, DISCORD_HEARTBEAT_ACK, DISCORD_HELLO, DISCORD_INVALID_SESSION, DISCORD_RECONNECT, gateway_handle_dispatch(), gateway_handle_identify(), gateway_send_heartbeat(), HEARTBEAT_INTERVAL, bot_client::heartbeat_latency, last_hearbeat, websocket_client::success_login, bot_client::websocket_client, and websocket_reconnect().
Referenced by disco_start_bot().
gateway_send_heartbeat()
static void gateway_send_heartbeat (websocket_client_t * client) static
References client, last_hearbeat, s, websocket_send(), and websocket_client::wsi.
Referenced by gateway_heartbeat_loop(), and gateway_on_receive().
Variable Documentation
HEARTBEAT_INTERVAL
unsigned int HEARTBEAT_INTERVAL = 10000 static
Referenced by gateway_heartbeat_loop(), and gateway_on_receive().
last_hearbeat
struct timeval last_hearbeat static
Referenced by gateway_on_receive(), and gateway_send_heartbeat().
s
int s = -1 static
Referenced by gateway_handle_dispatch(), gateway_send_heartbeat(), get_array_from_json(), and write_data().