Disco-C: include/web/gateway.h File Reference
gateway.h File Reference
#include <discord/disco.h>
Macros
#define DISCORD_DISPATCH 0
#define DISCORD_HEARTBEAT 1
#define DISCORD_IDENTIFY 2
#define DISCORD_PRESENCE_UPDATE 3
#define DISCORD_VOICE_STATE_UPDATE 4
#define DISCORD_RESUME 6
#define DISCORD_RECONNECT 7
#define DISCORD_REQUEST_GUILD_MEMBERS 8
#define DISCORD_INVALID_SESSION 9
#define DISCORD_HELLO 10
#define DISCORD_HEARTBEAT_ACK 11
Functions
void gateway_on_receive (bot_client_t *bot_client, char *data, size_t len)
Callback function for when a websocket package is received.
void * gateway_heartbeat_loop (void *vargp)
Initiates the heartbeat loop.
void gateway_event_loop (bot_client_t *bot)
Initiates the event loop.
Macro Definition Documentation
DISCORD_DISPATCH
#define DISCORD_DISPATCH 0
DISCORD_HEARTBEAT
#define DISCORD_HEARTBEAT 1
DISCORD_HEARTBEAT_ACK
#define DISCORD_HEARTBEAT_ACK 11
DISCORD_HELLO
#define DISCORD_HELLO 10
DISCORD_IDENTIFY
#define DISCORD_IDENTIFY 2
DISCORD_INVALID_SESSION
#define DISCORD_INVALID_SESSION 9
DISCORD_PRESENCE_UPDATE
#define DISCORD_PRESENCE_UPDATE 3
DISCORD_RECONNECT
#define DISCORD_RECONNECT 7
DISCORD_REQUEST_GUILD_MEMBERS
#define DISCORD_REQUEST_GUILD_MEMBERS 8
DISCORD_RESUME
#define DISCORD_RESUME 6
DISCORD_VOICE_STATE_UPDATE
#define DISCORD_VOICE_STATE_UPDATE 4
Function Documentation
gateway_event_loop()
void gateway_event_loop (bot_client_t * bot)
Initiates the event loop.
This is the main loop that needs to be run for the bot to work.
Parameters
bot Active bot instance
References websocket_client::active, websocket_client::context, and bot_client::websocket_client.
Referenced by discord_start_bot().
gateway_heartbeat_loop()
void* gateway_heartbeat_loop (void * vargp)
Initiates the heartbeat loop.
Intended to be run on a seperate thread.
Parameters
vargp Pointer to the active websocket client
Returns
void*
References websocket_client::active, client, d_log_debug, gateway_send_heartbeat(), websocket_client::heartbeat_active, and HEARTBEAT_INTERVAL.
Referenced by gateway_handle_identify().
gateway_on_receive()
void gateway_on_receive (bot_client_t * bot_client, char * data, size_t len)
Callback function for when a websocket package is received.
Parameters
bot_client A bot instance
data The data that was received
len The length of the data
References d_log_debug, d_log_err, d_log_notice, DISCORD_DISPATCH, DISCORD_HEARTBEAT, DISCORD_HEARTBEAT_ACK, DISCORD_HELLO, DISCORD_INVALID_SESSION, DISCORD_RECONNECT, gateway_handle_dispatch(), gateway_handle_identify(), gateway_send_heartbeat(), HEARTBEAT_INTERVAL, bot_client::heartbeat_latency, last_hearbeat, websocket_client::success_login, bot_client::websocket_client, and websocket_reconnect().
Referenced by discord_start_bot().