Disco-C: Permission
Permission
Models
Permission functions and structures.
Data Structures
struct discord_overwrite
https://discord.com/developers/docs/resources/channel#overwrite-object
Functions
void * _d_json_to_overwrite (cJSON *data)
Creates a permission overwrite structure from a given JSON.
struct discord_overwrite * _d_copy_overwrite (struct discord_overwrite *src)
Copies an overwrite structure.
void discord_destroy_overwrite (struct discord_overwrite *overwrite)
Destroys the given structure and frees the pointer.
Detailed Description
Permission functions and structures.
Function Documentation
_d_copy_overwrite()
struct discord_overwrite* _d_copy_overwrite (struct discord_overwrite * src)
Copies an overwrite structure.
Parameters
src Overwrite to copy.
Returns
struct discord_overwrite*
Referenced by _d_copy_channel().
_d_json_to_overwrite()
void* _d_json_to_overwrite (cJSON * data)
Creates a permission overwrite structure from a given JSON.
Parameters
data
Returns
void* discord_overwrite struct
Referenced by _d_json_to_channel().
discord_destroy_overwrite()
void discord_destroy_overwrite (struct discord_overwrite * overwrite)
Destroys the given structure and frees the pointer.
Parameters
overwrite
Referenced by discord_destroy_channel().