Disco-C: Message
Message
Models
Data Structures
struct discord_allowed_mentions
https://discord.com/developers/docs/resources/channel#allowed-mentions-object-allowed-mentions-structure
struct discord_message_reference
https://discord.com/developers/docs/resources/channel#message-reference-object
struct discord_create_message
https://discord.com/developers/docs/resources/channel#create-message
struct discord_message
https://discord.com/developers/docs/resources/channel#message-object
Enumerations
enum Discord_Message_Type {
DEFAULT, RECIPIENT_ADD, RECIPIENT_REMOVE, CALL,
CHANNEL_NAME_CHANGE, CHANNEL_ICON_CHANGE, CHANNEL_PINNED_MESSAGE, GUILD_MEMBER_JOIN,
USER_PREMIUM_GUILD_SUBSCRIPTION, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3,
CHANNEL_FOLLOW_ADD = 12, GUILD_DISCOVERY_DISQUALIFIED = 14, GUILD_DISCOVERY_REQUALIFIED, GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING,
GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING, THREAD_CREATED, REPLY, CHAT_INPUT_COMMAND,
THREAD_STARTER_MESSAGE, GUILD_INVITE_REMINDER, CONTEXT_MENU_COMMAND
}
https://discord.com/developers/docs/resources/channel#message-object-message-types
Functions
void * _d_json_to_message_reference (cJSON *data)
Creates a message_reference structure from a given JSON.
struct discord_message_reference * _d_copy_message_reference (struct discord_message_reference *src)
Copies a message reference structure.
void discord_destroy_message_reference (struct discord_message_reference *message)
Destroys the given structure and frees the pointer.
void * _d_json_to_message (cJSON *data)
Creates a message structure from a given JSON.
struct discord_message * _d_copy_message (struct discord_message *message)
Copies a message structure.
void discord_destroy_message (struct discord_message *message)
Destroys the given structure and frees the pointer.
void _d_create_message_to_json (cJSON *json, char *content, struct discord_create_message *message)
Fills in a JSON with the attributes of the message structure.
Detailed Description
Message functions and structures
Enumeration Type Documentation
Discord_Message_Type
enum Discord_Message_Type
https://discord.com/developers/docs/resources/channel#message-object-message-types
Enumerator
DEFAULT
RECIPIENT_ADD
RECIPIENT_REMOVE
CALL
CHANNEL_NAME_CHANGE
CHANNEL_ICON_CHANGE
CHANNEL_PINNED_MESSAGE
GUILD_MEMBER_JOIN
USER_PREMIUM_GUILD_SUBSCRIPTION
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3
CHANNEL_FOLLOW_ADD
GUILD_DISCOVERY_DISQUALIFIED
GUILD_DISCOVERY_REQUALIFIED
GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING
GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING
THREAD_CREATED
REPLY
CHAT_INPUT_COMMAND
THREAD_STARTER_MESSAGE
GUILD_INVITE_REMINDER
CONTEXT_MENU_COMMAND
Function Documentation
_d_copy_message()
struct discord_message* _d_copy_message (struct discord_message * message)
Copies a message structure.
Parameters
message Message to copy.
Returns
struct discord_message*
References _d_copy_application(), _d_copy_attachment(), _d_copy_channel(), _d_copy_component(), _d_copy_embed(), _d_copy_interaction(), _d_copy_member(), _d_copy_message_activity(), _d_copy_message_reference(), _d_copy_reaction(), _d_copy_sticker(), _d_copy_sticker_item(), _d_copy_user(), discord_message::activity, discord_message::application, discord_message::attachments, discord_message::attachments_count, discord_message::components, discord_message::components_count, discord_message::content, discord_message::edited_timestamp, discord_message::embeds, discord_message::embeds_count, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_roles, discord_message::mention_roles_count, discord_message::mentions, discord_message::mentions_count, discord_message::message_reference, discord_message::nonce, discord_message::reactions, discord_message::reactions_count, discord_message::referenced_message, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::thread, discord_message::timestamp, and discord_message::user.
Referenced by _d_copy_interaction(), and event_handle().
_d_copy_message_reference()
struct discord_message_reference* _d_copy_message_reference (struct discord_message_reference * src)
Copies a message reference structure.
Parameters
message Message reference to copy.
Returns
struct discord_message_reference*
Referenced by _d_copy_message().
_d_create_message_to_json()
void _d_create_message_to_json (cJSON * json, char * content, struct discord_create_message * message)
Fills in a JSON with the attributes of the message structure.
Parameters
json JSON struct that should be filled in with the values.
content Discord message content.
message Create message struct.
References discord_create_message::allowed_mentions, discord_create_message::attachments, discord_create_message::attachments_count, create_allowed_mentions(), create_embed_json(), create_message_reference(), discord_attachment::description, discord_create_message::embed, discord_create_message::embeds, discord_create_message::embeds_count, discord_attachment::filename, discord_create_message::flags, discord_create_message::message_reference, discord_create_message::sticker_ids, and discord_create_message::sticker_ids_count.
Referenced by discord_channel_send_message(), discord_send_interaction(), and test_message_creation().
_d_json_to_message()
void* _d_json_to_message (cJSON * data)
Creates a message structure from a given JSON.
Parameters
data
Returns
void* discord_message struct
References _d_get_array_from_json(), _d_get_bool_from_json(), _d_get_int_from_json(), _d_get_long_from_string_json(), _d_get_string_from_json(), _d_json_to_application(), _d_json_to_attachment(), _d_json_to_channel_mention(), _d_json_to_component(), _d_json_to_interaction(), _d_json_to_member(), _d_json_to_message_activity(), _d_json_to_message_reference(), _d_json_to_reaction(), _d_json_to_sticker(), _d_json_to_sticker_item(), _d_json_to_user(), discord_message::activity, discord_message::application, discord_message::application_id, discord_message::attachments, discord_message::attachments_count, discord_message::channel_id, discord_message::components, discord_message::components_count, discord_message::content, discord_interaction::data, discord_message::flags, discord_message::guild_id, discord_message::id, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_everyone, discord_message::mention_roles, discord_message::mention_roles_count, discord_message::mentions, discord_message::mentions_count, discord_message::message_reference, discord_message::nonce, discord_message::pinned, discord_message::reactions, discord_message::reactions_count, discord_message::referenced_message, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::timestamp, discord_message::tts, discord_message::type, discord_message::user, and discord_message::webhook_id.
Referenced by _d_json_to_interaction(), event_handle(), and request_t_pool().
_d_json_to_message_reference()
void* _d_json_to_message_reference (cJSON * data)
Creates a message_reference structure from a given JSON.
Parameters
data
Returns
void* discord_message_reference struct.
References _d_get_long_from_string_json(), discord_message_reference::channel_id, discord_message_reference::guild_id, and discord_message_reference::message_id.
Referenced by _d_json_to_message().
discord_destroy_message()
void discord_destroy_message (struct discord_message * message)
Destroys the given structure and frees the pointer.
Parameters
message
References discord_message::activity, discord_message::application, discord_message::attachments, discord_message::attachments_count, discord_message::components, discord_message::components_count, discord_message::content, discord_destroy_application(), discord_destroy_attachment(), discord_destroy_channel(), discord_destroy_component(), discord_destroy_embed(), discord_destroy_interaction(), discord_destroy_member(), discord_destroy_message_activity(), discord_destroy_message_reference(), discord_destroy_message_sticker_item(), discord_destroy_reaction(), discord_destroy_sticker(), discord_destroy_user(), discord_message::edited_timestamp, discord_message::embeds, discord_message::embeds_count, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_roles, discord_message::mentions, discord_message::mentions_count, discord_message::message_reference, discord_message::nonce, discord_message::reactions, discord_message::reactions_count, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::thread, discord_message::timestamp, and discord_message::user.
Referenced by default_destroy_callback(), and discord_destroy_interaction().
discord_destroy_message_reference()
void discord_destroy_message_reference (struct discord_message_reference * message)
Destroys the given structure and frees the pointer.
Parameters
message
Referenced by discord_destroy_message().