Disco-C: Message_Commands
Message_Commands
Commands
Data Structures
struct discord_message_cb
Discord Message Callback.
struct discord_multiple_message_cb
Functions
void discord_channel_send_message (bot_client_t *bot, char *content, uint64_t channel_id, struct discord_create_message *message, struct discord_message_cb *cb)
Sends a message and if enabled also returns the sent message struct.
void discord_channel_edit_message (bot_client_t *bot, char *content, uint64_t channel_id, uint64_t message_id, struct discord_create_message *message)
Edit a message.
void discord_get_messages (bot_client_t *bot, uint64_t channel_id, int limit, uint64_t around, uint64_t before, uint64_t after, struct discord_multiple_message_cb *cb)
Returns an array of Discord message structs.
void discord_get_message (bot_client_t *bot, uint64_t channel_id, uint64_t message_id, struct discord_message_cb *cb)
Returns a specific message by channel and message ID.
void discord_fetch_message (bot_client_t *bot, uint64_t channel_id, uint64_t message_id, struct discord_message_cb *cb)
Fetches the message from Discord without first checking if it's in the cache.
Detailed Description
Function Documentation
discord_channel_edit_message()
void discord_channel_edit_message (bot_client_t * bot, char * content, uint64_t channel_id, uint64_t message_id, struct discord_create_message * message)
Edit a message.
Parameters
bot Active bot instance.
content Message content to edit to.
channel_id Channel ID of the message.
message_id Message ID to edit.
message struct discord_create_message Create message to edit to. Can be NULL.
References discord_create_message::allowed_mentions, discord_create_message::attachments, discord_create_message::attachments_count, create_allowed_mentions(), create_embed_json(), discord_create_message::embed, discord_create_message::embeds, discord_create_message::embeds_count, discord_attachment::filename, discord_create_message::flags, request(), REQUEST_PATCH, websocket_client::token, and bot_client::websocket_client.
discord_channel_send_message()
void discord_channel_send_message (bot_client_t * bot, char * content, uint64_t channel_id, struct discord_create_message * message, struct discord_message_cb * cb)
Sends a message and if enabled also returns the sent message struct.
Parameters
bot Active bot instance.
content Message content to send (if empty, embed or components need to exist).
channel_id ID of the channel the message should be sent in.
message A discord_create_message struct. Can be NULL.
cb discord_message_cb struct which contains a callback that will be called with the given data. Can be NULL to ignore.
References _d_create_message_to_json(), discord_create_message::attachments, discord_create_message::attachments_count, request_callback::cb_struct, discord_message_reference::channel_id, DISCORD_MESSAGE_CALLBACK, discord_attachment::filename, request(), REQUEST_POST, websocket_client::token, request_callback::type, and bot_client::websocket_client.
discord_fetch_message()
void discord_fetch_message (bot_client_t * bot, uint64_t channel_id, uint64_t message_id, struct discord_message_cb * cb)
Fetches the message from Discord without first checking if it's in the cache.
The message will be added to the cache if it doesn't exist yet. discord_get_message is preferred over this fetch function, because this will force a new entry to the cache on every call. Deleted messages won't be retrieved.
Parameters
bot Active bot instance.
channel_id Channel to fetch message from.
message_id Message to fetch.
References request_callback::cb_struct, discord_message::channel_id, DISCORD_MESSAGE_CALLBACK, request(), REQUEST_GET, websocket_client::token, request_callback::type, and bot_client::websocket_client.
Referenced by discord_get_message().
discord_get_message()
void discord_get_message (bot_client_t * bot, uint64_t channel_id, uint64_t message_id, struct discord_message_cb * cb)
Returns a specific message by channel and message ID.
This function first checks the cache and returns whatever is in the cache if it exists. This function has the upside that deleted messages can be retrieved if they're still in the cache.
Parameters
bot Active bot instance.
channel_id Channel to fetch message from.
message_id Message to fetch.
References discord_message_cb::cb, discord_message::channel_id, discord_message_cb::data, discord_cache_get_message(), and discord_fetch_message().
discord_get_messages()
void discord_get_messages (bot_client_t * bot, uint64_t channel_id, int limit, uint64_t around, uint64_t before, uint64_t after, struct discord_multiple_message_cb * cb)
Returns an array of Discord message structs.
The parameters around, before and after are mutually exclusive, only one may be passed at a time. All the retrieved messages will be placed into the cache. NOTE: Messages don't have to be destroyed as they are all in the cache. Only the array itself has to be freed.
Parameters
bot Active bot instance.
channel_id Channel to fetch messages from.
limit Max number of messages to return (1-100). 0 to ignore and use the default of 50.
around Get messages around this message ID. 0 to ignore.
before Get messages before this message ID. 0 to ignore.
after Get messages after this message ID. 0 to ignore.
cb Callback struct which is called once ther request is done.
References request_callback::cb_struct, DISCORD_MULTIPLE_MESSAGE_CALLBACK, request(), REQUEST_GET, websocket_client::token, request_callback::type, and bot_client::websocket_client.