Disco-C: Client
Client
Data Structures
struct discord_event_callbacks
struct bot_client
struct discord_config
Discord configs which will be set when starting the bot.
Typedefs
typedef struct discord_event_callbacks discord_event_callbacks_t
Functions
void discord_start_bot (discord_event_callbacks_t *callbacks, const char *token, struct discord_config *config)
High level abstraction which starts the bot.
void discord_free_bot (bot_client_t *bot)
Frees up memory for a bot instance.
Detailed Description
The main Discord client that will be used everywhere.
Typedef Documentation
discord_event_callbacks_t
typedef struct discord_event_callbacks discord_event_callbacks_t
Function Documentation
discord_free_bot()
void discord_free_bot (bot_client_t * bot)
Frees up memory for a bot instance.
Parameters
bot Bot instance
discord_start_bot()
void discord_start_bot (discord_event_callbacks_t * callbacks, const char * token, struct discord_config * config)
High level abstraction which starts the bot.
Parameters
callbacks A callbacks object containing the callbacks to the event functions.
token Bot token as a string
config Optional additional config settings. Can be NULL to resort to the default configs.
References bot_client::callbacks, discord_config::channel_cache_size, client, d_log_err, discord_cache_destroy(), discord_cache_init(), discord_destroy_user(), gateway_event_loop(), gateway_on_receive(), discord_config::guild_cache_size, discord_config::message_cache_size, sighandle(), t_pool_destroy(), t_pool_init(), t_process_count(), bot_client::thread_pool, websocket_client::token, bot_client::user, bot_client::websocket_client, websocket_connect(), websocket_create(), and websocket_destroy_client().