Disco-C: Thread
Thread
Models
Data Structures
struct discord_thread_metadata
https://discord.com/developers/docs/resources/channel#thread-metadata-object
struct discord_thread_member
https://discord.com/developers/docs/resources/channel#thread-member-object
Functions
void * _d_json_to_thread_metadata (cJSON *data)
Creates a thread metadata structure from a given JSON.
struct discord_thread_metadata * _d_copy_thread_metadata (struct discord_thread_metadata *src)
Copies a thread metadata structure.
void discord_destroy_thread_metadata (struct discord_thread_metadata *thread)
Destroys the given structure and frees the pointer.
void * _d_json_to_thread_member (cJSON *data)
Creates a thread member structure from a given JSON.
struct discord_thread_member * _d_copy_thread_member (struct discord_thread_member *src)
Copies a thread member structure.
void discord_destroy_thread_member (struct discord_thread_member *member)
Destroys the given structure and frees the pointer.
Detailed Description
Thread functions and structures
Function Documentation
_d_copy_thread_member()
struct discord_thread_member* _d_copy_thread_member (struct discord_thread_member * src)
Copies a thread member structure.
Parameters
src Thread member to copy.
Returns
struct discord_thread_member*
Referenced by _d_copy_channel().
_d_copy_thread_metadata()
struct discord_thread_metadata* _d_copy_thread_metadata (struct discord_thread_metadata * src)
Copies a thread metadata structure.
Parameters
src Thread metadata to copy.
Returns
struct discord_thread_metadata*
Referenced by _d_copy_channel().
_d_json_to_thread_member()
void* _d_json_to_thread_member (cJSON * data)
Creates a thread member structure from a given JSON.
Parameters
data
Returns
void* discord_thread_member struct
Referenced by _d_json_to_channel().
_d_json_to_thread_metadata()
void* _d_json_to_thread_metadata (cJSON * data)
Creates a thread metadata structure from a given JSON.
Parameters
data
Returns
void* discord_thread_metadata struct
Referenced by _d_json_to_channel().
discord_destroy_thread_member()
void discord_destroy_thread_member (struct discord_thread_member * member)
Destroys the given structure and frees the pointer.
Parameters
member
discord_destroy_thread_metadata()
void discord_destroy_thread_metadata (struct discord_thread_metadata * thread)
Destroys the given structure and frees the pointer.
Parameters
thread