Disco-C: Component
Component
Models
Component functions and structures.
Data Structures
struct discord_action_row
https://discord.com/developers/docs/interactions/message-components#action-rows
struct discord_button
https://discord.com/developers/docs/interactions/message-components#button-object
struct discord_select_option
https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-option-structure
struct discord_select_menu
https://discord.com/developers/docs/interactions/message-components#select-menu-object
struct discord_text_input
https://discord.com/developers/docs/interactions/message-components#text-inputs-text-input-structure
struct discord_component
https://discord.com/developers/docs/interactions/message-components#component-object
Enumerations
enum Discord_Component_Type { COMPONENT_ACTION_ROW = 1 , COMPONENT_BUTTON = 2 , COMPONENT_SELECT_MENU = 3 , COMPONENT_TEXT_INPUT = 4 }
enum Discord_Button_Style {
BUTTON_PRIMARY = 1 , BUTTON_SECONDARY = 2 , BUTTON_SUCCESS = 3 , BUTTON_DANGER = 4 ,
BUTTON_LINK = 5
}
enum Discord_Text_Input_Style { TEXT_INPUT_SHORT = 1 , TEXT_INPUT_PARAGRAPH = 2 }
Functions
void * _d_json_to_select_option (cJSON *data)
Creates a select option structure from a given JSON.
struct discord_select_option * _d_copy_select_option (struct discord_select_option *src)
Copies a select option structure.
void discord_destroy_select_option (struct discord_select_option *option)
Destroys the given structure and frees the pointer.
void * _d_json_to_component (cJSON *data)
Creates a component structure from a given JSON with the correct type.
struct discord_component * _d_copy_component (struct discord_component *src)
Copies a component structure.
void discord_destroy_component (struct discord_component *c)
Destroys the given structure and frees the pointer.
void _d_component_to_json (cJSON *json, struct discord_component *component)
Fills in a JSON with the attributes of the component structure.
Detailed Description
Component functions and structures.
Enumeration Type Documentation
Discord_Button_Style
enum Discord_Button_Style
Enumerator
BUTTON_PRIMARY
BUTTON_SECONDARY
BUTTON_SUCCESS
BUTTON_DANGER
BUTTON_LINK
Discord_Component_Type
enum Discord_Component_Type
Enumerator
COMPONENT_ACTION_ROW
COMPONENT_BUTTON
COMPONENT_SELECT_MENU
COMPONENT_TEXT_INPUT
Discord_Text_Input_Style
enum Discord_Text_Input_Style
Enumerator
TEXT_INPUT_SHORT
TEXT_INPUT_PARAGRAPH
Function Documentation
_d_component_to_json()
void _d_component_to_json (cJSON * json, struct discord_component * component)
Fills in a JSON with the attributes of the component structure.
Parameters
json JSON struct that should be filled in with the values.
component The component that will be used to fill the JSON.
Referenced by discord_send_interaction().
_d_copy_component()
struct discord_component* _d_copy_component (struct discord_component * src)
Copies a component structure.
Parameters
src Component to copy.
Returns
struct discord_component*
References _d_copy_component(), _d_copy_emoji(), _d_copy_select_option(), discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, discord_button::disabled, discord_button::emoji, discord_button::label, discord_text_input::label, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_component::select_menu, discord_button::style, discord_component::text_input, discord_component::type, discord_button::url, and discord_text_input::value.
Referenced by _d_copy_component(), _d_copy_interaction_data(), and _d_copy_message().
_d_copy_select_option()
struct discord_select_option* _d_copy_select_option (struct discord_select_option * src)
Copies a select option structure.
Parameters
src Select option to copy.
Returns
struct discord_select option*
References _d_copy_emoji(), discord_select_option::_default, discord_select_option::description, discord_select_option::emoji, discord_select_option::label, and discord_select_option::value.
Referenced by _d_copy_component().
_d_json_to_component()
void* _d_json_to_component (cJSON * data)
Creates a component structure from a given JSON with the correct type.
Parameters
data
Returns
void* discord_component struct
References _d_get_array_from_json(), _d_get_bool_from_json(), _d_get_int_from_json(), _d_get_string_from_json(), _d_json_to_component(), _d_json_to_emoji(), _d_json_to_select_option(), discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, discord_button::disabled, discord_select_menu::disabled, discord_button::emoji, discord_button::label, discord_text_input::label, discord_text_input::max_length, discord_select_menu::max_values, discord_text_input::min_length, discord_select_menu::min_values, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_text_input::required, discord_component::select_menu, discord_button::style, discord_text_input::style, discord_component::text_input, discord_button::url, and discord_text_input::value.
Referenced by _d_json_to_component(), _d_json_to_interaction_data(), and _d_json_to_message().
_d_json_to_select_option()
void* _d_json_to_select_option (cJSON * data)
Creates a select option structure from a given JSON.
Parameters
data
Returns
void* discord_select_option struct
References _d_get_bool_from_json(), _d_get_string_from_json(), _d_json_to_emoji(), discord_select_option::_default, discord_select_option::description, discord_select_option::emoji, discord_select_option::label, and discord_select_option::value.
Referenced by _d_json_to_component(), and _d_json_to_interaction_data().
discord_destroy_component()
void discord_destroy_component (struct discord_component * c)
Destroys the given structure and frees the pointer.
Parameters
c discord_component struct
References discord_component::action_row, discord_component::button, discord_component::comp, COMPONENT_ACTION_ROW, COMPONENT_BUTTON, COMPONENT_SELECT_MENU, COMPONENT_TEXT_INPUT, discord_action_row::components, discord_action_row::components_count, discord_button::custom_id, discord_select_menu::custom_id, discord_text_input::custom_id, discord_destroy_component(), discord_destroy_emoji(), discord_destroy_select_option(), discord_button::emoji, discord_button::label, discord_text_input::label, discord_select_menu::options, discord_select_menu::options_count, discord_select_menu::placeholder, discord_text_input::placeholder, discord_component::select_menu, discord_component::text_input, discord_component::type, discord_button::url, and discord_text_input::value.
Referenced by discord_destroy_component(), discord_destroy_interaction_data(), and discord_destroy_message().
discord_destroy_select_option()
void discord_destroy_select_option (struct discord_select_option * option)
Destroys the given structure and frees the pointer.
Parameters
option
References discord_select_option::description, discord_destroy_emoji(), discord_select_option::emoji, discord_select_option::label, and discord_select_option::value.
Referenced by discord_destroy_component().