Disco-C: Command
Command
Models
Data Structures
struct discord_language_locales
struct discord_application_command_option_choice
struct discord_application_command_option
struct discord_application_command
Enumerations
enum Discord_Application_Command_Type { COMMAND_CHAT_INPUT = 1, COMMAND_USER = 2, COMMAND_MESSAGE = 3 }
enum Discord_Application_Command_Option_Type {
COMMAND_OPTION_SUB_COMMAND = 1, COMMAND_OPTION_SUB_COMMAND_GROUP = 2, COMMAND_OPTION_STRING = 3, COMMAND_OPTION_INTEGER = 4,
COMMAND_OPTION_BOOLEAN = 5, COMMAND_OPTION_USER = 6, COMMAND_OPTION_CHANNEL = 7, COMMAND_OPTION_ROLE = 8,
COMMAND_OPTION_MENTIONABLE = 9, COMMAND_OPTION_NUMBER = 10, COMMAND_OPTION_ATTACHMENT = 11
}
Functions
void discord_fill_json_with_locales (cJSON *json, struct discord_language_locales *locales)
Fills a JSON with the values of a langauge locales struct.
int discord_command_register (struct discord_application_command *command, const char *token)
int discord_command_update (struct discord_application_command *command, int64_t command_id, const char *token)
int discord_command_delete_global (int64_t command_id, const char *token)
int discord_command_delete_guild (int64_t guild_id, int64_t command_id, const char *token)
Detailed Description
Command functions and structures
Enumeration Type Documentation
Discord_Application_Command_Option_Type
enum Discord_Application_Command_Option_Type
Enumerator
COMMAND_OPTION_SUB_COMMAND
COMMAND_OPTION_SUB_COMMAND_GROUP
COMMAND_OPTION_STRING
COMMAND_OPTION_INTEGER
COMMAND_OPTION_BOOLEAN
COMMAND_OPTION_USER
COMMAND_OPTION_CHANNEL
COMMAND_OPTION_ROLE
COMMAND_OPTION_MENTIONABLE
COMMAND_OPTION_NUMBER
COMMAND_OPTION_ATTACHMENT
Discord_Application_Command_Type
enum Discord_Application_Command_Type
Enumerator
COMMAND_CHAT_INPUT
COMMAND_USER
COMMAND_MESSAGE
Function Documentation
discord_command_delete_global()
int discord_command_delete_global (int64_t command_id, const char * token)
References request(), and REQUEST_DELETE.
discord_command_delete_guild()
int discord_command_delete_guild (int64_t guild_id, int64_t command_id, const char * token)
References request(), and REQUEST_DELETE.
discord_command_register()
int discord_command_register (struct discord_application_command * command, const char * token)
References d_log_notice, format_json(), discord_application_command::guild_id, request(), and REQUEST_POST.
discord_command_update()
int discord_command_update (struct discord_application_command * command, int64_t command_id, const char * token)
References format_json(), discord_application_command::guild_id, request(), and REQUEST_PATCH.
discord_fill_json_with_locales()
void discord_fill_json_with_locales (cJSON * json, struct discord_language_locales * locales)
Fills a JSON with the values of a langauge locales struct.
Parameters
json JSON struct to fill the values in.
locales struct to be used to fill in the JSON.
References discord_language_locales::bg, discord_language_locales::cs, discord_language_locales::da, discord_language_locales::de, discord_language_locales::el, discord_language_locales::en_GB, discord_language_locales::en_US, discord_language_locales::es_ES, discord_language_locales::fi, discord_language_locales::fr, discord_language_locales::hi, discord_language_locales::hr, discord_language_locales::hu, discord_language_locales::it, discord_language_locales::ja, discord_language_locales::ko, discord_language_locales::lt, discord_language_locales::nl, discord_language_locales::no, discord_language_locales::pl, discord_language_locales::pt_BR, discord_language_locales::ro, discord_language_locales::ru, discord_language_locales::sv_SE, discord_language_locales::th, discord_language_locales::tr, discord_language_locales::uk, discord_language_locales::vi, discord_language_locales::zh_CN, and discord_language_locales::zh_TW.
Referenced by add_choice(), add_option(), discord_send_interaction(), and format_json().