Disco-C: Interaction
Interaction
Models
Data Structures
struct discord_interaction_data_option
struct discord_interaction_data
struct discord_interaction
struct discord_interaction_callback
Enumerations
enum Discord_Interaction_Type {
INTERACTION_PING = 1, INTERACTION_APPLICATION_COMMAND = 2, INTERACTION_MESSAGE_COMPONENT = 3, INTERACTION_APPLICATION_COMMAND_AUTOCOMPLETE = 4,
INTERACTION_MODAL_SUBMIT = 5
}
enum Value_Type { VALUE_STRING, VALUE_INTEGER, VALUE_DOUBLE }
enum Discord_Interaction_Callback_Type {
DISCORD_CALLBACK_PONG = 1, DISCORD_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE = 4, DISCORD_CALLBACK_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5, DISCORD_CALLBACK_DEFERRED_UPDATE_MESSAGE = 6,
DISCORD_CALLBACK_UPDATE_MESSAGE = 7, DISCORD_CALLBACK_APPLICATION_COMMAND_AUTOCOMPLETE_RESULT = 8, DISCORD_CALLBACK_MODAL = 9
}
Functions
void * discord_create_interaction_data_option_struct_json (cJSON *data)
void discord_destroy_interaction_data_option (struct discord_interaction_data_option *interaction)
void * discord_create_interaction_data_struct_json (cJSON *data)
void discord_destroy_interaction_data (struct discord_interaction_data *interaction)
void * discord_create_interaction_struct_json (cJSON *data)
void discord_destroy_interaction (struct discord_interaction *interaction)
void discord_fill_json_interaction_callback (cJSON *json, struct discord_interaction_callback *callback)
void discord_send_interaction (bot_client_t *bot, struct discord_interaction_callback *cb, struct discord_interaction *received_interaction)
Detailed Description
Interaction functions and structures
Enumeration Type Documentation
Discord_Interaction_Callback_Type
enum Discord_Interaction_Callback_Type
Enumerator
DISCORD_CALLBACK_PONG
DISCORD_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE
DISCORD_CALLBACK_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE
DISCORD_CALLBACK_DEFERRED_UPDATE_MESSAGE
DISCORD_CALLBACK_UPDATE_MESSAGE
DISCORD_CALLBACK_APPLICATION_COMMAND_AUTOCOMPLETE_RESULT
DISCORD_CALLBACK_MODAL
Discord_Interaction_Type
enum Discord_Interaction_Type
Enumerator
INTERACTION_PING
INTERACTION_APPLICATION_COMMAND
INTERACTION_MESSAGE_COMPONENT
INTERACTION_APPLICATION_COMMAND_AUTOCOMPLETE
INTERACTION_MODAL_SUBMIT
Value_Type
enum Value_Type
Enumerator
VALUE_STRING
VALUE_INTEGER
VALUE_DOUBLE
Function Documentation
discord_create_interaction_data_option_struct_json()
void* discord_create_interaction_data_option_struct_json (cJSON * data)
References COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, COMMAND_OPTION_STRING, discord_interaction_data_option::double_, discord_interaction_data_option::focused, get_array_from_json(), get_bool_from_json(), get_double_from_string_json(), get_int_from_json(), get_string_from_json(), discord_interaction_data_option::int_, discord_interaction_data_option::name, discord_interaction_data_option::options, discord_interaction_data_option::options_count, discord_interaction_data_option::string_, discord_interaction_data_option::type, and discord_interaction_data_option::value.
Referenced by discord_create_interaction_data_struct_json().
discord_create_interaction_data_struct_json()
void* discord_create_interaction_data_struct_json (cJSON * data)
References discord_interaction_data::components, discord_interaction_data::components_count, discord_interaction_data::custom_id, discord_create_component_struct_json(), discord_create_interaction_data_option_struct_json(), discord_create_select_option_struct(), get_array_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_interaction_data::guild_id, discord_interaction_data::id, discord_interaction_data::name, discord_interaction_data::options, discord_interaction_data::options_count, discord_interaction_data::target_id, discord_interaction_data::type, discord_interaction_data::values, and discord_interaction_data::values_count.
Referenced by discord_create_interaction_struct_json().
discord_create_interaction_struct_json()
void* discord_create_interaction_struct_json (cJSON * data)
References discord_interaction::app_permissions, discord_interaction::application_id, discord_interaction::channel_id, discord_interaction::data, discord_create_interaction_data_struct_json(), discord_create_member_struct_json(), discord_create_message_struct_json(), discord_create_user_struct_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_interaction::guild_id, discord_interaction::guild_locale, discord_interaction::id, discord_interaction::locale, discord_interaction::member, discord_interaction::message, discord_interaction::token, discord_interaction::type, discord_interaction::user, and discord_interaction::version.
Referenced by discord_create_message_struct_json(), and event_handle().
discord_destroy_interaction()
void discord_destroy_interaction (struct discord_interaction * interaction)
References discord_interaction::app_permissions, discord_interaction::data, discord_destroy_interaction_data(), discord_destroy_member(), discord_destroy_message(), discord_destroy_user(), discord_interaction::guild_locale, discord_interaction::locale, discord_interaction::member, discord_interaction::message, discord_interaction::token, and discord_interaction::user.
Referenced by discord_destroy_message().
discord_destroy_interaction_data()
void discord_destroy_interaction_data (struct discord_interaction_data * interaction)
References discord_interaction_data::components, discord_interaction_data::components_count, discord_interaction_data::custom_id, discord_destroy_component(), discord_destroy_interaction_data_option(), discord_interaction_data::name, discord_interaction_data::options, discord_interaction_data::options_count, discord_interaction_data::values, and discord_interaction_data::values_count.
Referenced by discord_destroy_interaction().
discord_destroy_interaction_data_option()
void discord_destroy_interaction_data_option (struct discord_interaction_data_option * interaction)
References COMMAND_OPTION_STRING, discord_interaction_data_option::name, discord_interaction_data_option::options, discord_interaction_data_option::options_count, discord_interaction_data_option::string_, discord_interaction_data_option::type, and discord_interaction_data_option::value.
Referenced by discord_destroy_interaction_data().
discord_fill_json_interaction_callback()
void discord_fill_json_interaction_callback (cJSON * json, struct discord_interaction_callback * callback)
discord_send_interaction()
void discord_send_interaction (bot_client_t * bot, struct discord_interaction_callback * cb, struct discord_interaction * received_interaction)
References discord_create_message::allowed_mentions, discord_create_message::attachments, discord_create_message::attachments_count, discord_interaction_callback::autocomplete, COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, COMMAND_OPTION_STRING, discord_create_message::components, discord_create_message::components_count, d_log_debug, d_log_err, discord_interaction::data, discord_interaction_callback::data, DISCORD_CALLBACK_APPLICATION_COMMAND_AUTOCOMPLETE_RESULT, DISCORD_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE, DISCORD_CALLBACK_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE, DISCORD_CALLBACK_DEFERRED_UPDATE_MESSAGE, DISCORD_CALLBACK_MODAL, DISCORD_CALLBACK_PONG, DISCORD_CALLBACK_UPDATE_MESSAGE, discord_fill_json_with_component(), discord_fill_json_with_locales(), discord_fill_json_with_message(), discord_create_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, discord_interaction::id, discord_interaction_callback::message, discord_interaction_callback::modal, discord_interaction_data::options, request(), REQUEST_POST, websocket_client::token, discord_interaction::token, discord_create_message::tts, discord_interaction_data_option::type, discord_interaction_callback::type, and bot_client::websocket_client.