Disco-C: Member
Member
Models
Data Structures
struct discord_member
Discord guild member structure.
Functions
void * _d_json_to_member (cJSON *data, struct discord_user *user)
Creates a discord_member struct with the passed in JSON.
struct discord_member * _d_copy_member (struct discord_member *member, struct discord_user *user)
Copies a member structure.
void discord_destroy_member (struct discord_member *member)
Detailed Description
Member functions and structures
Function Documentation
_d_copy_member()
struct discord_member* _d_copy_member (struct discord_member * member, struct discord_user * user)
Copies a member structure.
Parameters
member Member to copy.
user User to add to the member struct. Doesn't get copied again.
Returns
struct discord_member*
References discord_member::avatar, discord_member::communication_disabled_until, discord_member::joined_at, discord_member::nick, discord_member::permissions, discord_member::premium_since, discord_member::roles, discord_member::roles_count, and discord_member::user.
Referenced by _d_copy_interaction(), and _d_copy_message().
_d_json_to_member()
void* _d_json_to_member (cJSON * data, struct discord_user * user)
Creates a discord_member struct with the passed in JSON.
Parameters
data The Discord JSON for a member.
Returns
struct discord_member*
References _d_get_bool_from_json(), _d_get_string_from_json(), _d_json_to_user(), discord_member::avatar, discord_member::communication_disabled_until, discord_member::deaf, discord_member::joined_at, discord_member::mute, discord_member::nick, discord_member::pending, discord_member::permissions, discord_member::premium_since, discord_member::roles, discord_member::roles_count, and discord_member::user.
Referenced by _d_json_to_interaction(), and _d_json_to_message().
discord_destroy_member()
void discord_destroy_member (struct discord_member * member)
References discord_member::avatar, discord_member::communication_disabled_until, discord_destroy_user(), discord_member::joined_at, discord_member::nick, discord_member::permissions, discord_member::premium_since, discord_member::roles, and discord_member::user.
Referenced by discord_destroy_interaction(), and discord_destroy_message().