Disco-C: User
User
Models
User functions and structures.
Data Structures
struct discord_user
https://discord.com/developers/docs/resources/user#user-object
Functions
void * _d_json_to_user (cJSON *data)
Creates a discord_user struct with the passed in JSON.
struct discord_user * _d_copy_user (struct discord_user *user)
Copies a user structure.
void discord_destroy_user (struct discord_user *user)
Destroys the discord_user structs and frees the passed in pointer.
Detailed Description
User functions and structures.
Function Documentation
_d_copy_user()
struct discord_user* _d_copy_user (struct discord_user * user)
Copies a user structure.
Parameters
user User to copy.
Returns
struct discord_user*
References discord_user::avatar, discord_user::banner, discord_user::discriminator, discord_user::email, discord_user::locale, and discord_user::username.
Referenced by _d_copy_channel(), _d_copy_interaction(), and _d_copy_message().
_d_json_to_user()
void* _d_json_to_user (cJSON * data)
Creates a discord_user struct with the passed in JSON.
Parameters
data The Discord JSON for a user
Returns
struct discord_user*
References _d_get_bool_from_json(), _d_get_int_from_json(), _d_get_long_from_string_json(), _d_get_string_from_json(), discord_user::accent_color, discord_user::avatar, discord_user::banner, discord_user::bot, discord_user::discriminator, discord_user::email, discord_user::flags, discord_user::id, discord_user::locale, discord_user::mfa_enabled, discord_user::premium_type, discord_user::public_flags, discord_user::system, discord_user::username, and discord_user::verified.
Referenced by _d_json_to_channel(), _d_json_to_interaction(), _d_json_to_member(), _d_json_to_message(), and event_handle().
discord_destroy_user()
void discord_destroy_user (struct discord_user * user)
Destroys the discord_user structs and frees the passed in pointer.
Parameters
user
References discord_user::avatar, discord_user::banner, discord_user::discriminator, discord_user::email, discord_user::locale, and discord_user::username.
Referenced by discord_destroy_channel(), discord_destroy_interaction(), discord_destroy_member(), discord_destroy_message(), discord_start_bot(), and event_handle().