Disco-C: Commands
Commands
Modules
Message_Commands
Variables
void * discord_message_cb::data
Data that will be passed along the callback function.
void(* discord_message_cb::cb)(bot_client_t *, struct discord_message *, void *data)
void * discord_multiple_message_cb::data
void(* discord_multiple_message_cb::cb)(bot_client_t *, size_t size, struct discord_message **arr, void *data)
Detailed Description
Variable Documentation
cb [1/2]
void(* discord_multiple_message_cb::cb) (bot_client_t *, size_t size, struct discord_message **arr, void *data)
Referenced by request_t_pool().
cb [2/2]
void(* discord_message_cb::cb) (bot_client_t *, struct discord_message *, void *data)
Referenced by discord_get_message(), and request_t_pool().
data [1/2]
void* discord_message_cb::data
Data that will be passed along the callback function.
Referenced by discord_get_message().
data [2/2]
void* discord_multiple_message_cb::data
Referenced by request_t_pool().