Disco-C: Reaction
Reaction
Models
Reaction functions and structures.
Data Structures
struct discord_reaction
https://discord.com/developers/docs/resources/channel#reaction-object
Functions
void * _d_json_to_reaction (cJSON *data)
Creates a reaction structure from a given JSON.
struct discord_reaction * _d_copy_reaction (struct discord_reaction *reaction)
Copies a reaction structure.
void discord_destroy_reaction (struct discord_reaction *reaction)
Destroys the given structure and frees the pointer.
Detailed Description
Reaction functions and structures.
Function Documentation
_d_copy_reaction()
struct discord_reaction* _d_copy_reaction (struct discord_reaction * reaction)
Copies a reaction structure.
Parameters
reaction Reaction to copy.
Returns
struct discord_reaction*
Referenced by _d_copy_message().
_d_json_to_reaction()
void* _d_json_to_reaction (cJSON * data)
Creates a reaction structure from a given JSON.
Parameters
data
Returns
void* discord_reaction struct
Referenced by _d_json_to_message().
discord_destroy_reaction()
void discord_destroy_reaction (struct discord_reaction * reaction)
Destroys the given structure and frees the pointer.
Parameters
reaction
Referenced by discord_destroy_message().