Disco-C: Sticker
Sticker
Models
Sticker functions and structures.
Data Structures
struct discord_message_sticker_item
https://discord.com/developers/docs/resources/sticker#sticker-item-object
struct discord_sticker
https://discord.com/developers/docs/resources/sticker#sticker-object
Enumerations
enum Discord_Sticker_Format { STICKER_FORMAT_PNG = 1 , STICKER_FORMAT_APNG = 2 , STICKER_FORMAT_LOTTIE = 3 }
enum Discord_Sticker_Type { STICKER_TYPE_STANDARD = 1 , STICKER_TYPE_GUILD = 2 }
Functions
void * _d_json_to_sticker_item (cJSON *data)
Creates a sticker struct item with the given JSON.
struct discord_message_sticker_item * _d_copy_sticker_item (struct discord_message_sticker_item *src)
Copies a sticker item structure.
void discord_destroy_message_sticker_item (struct discord_message_sticker_item *message_sticker)
Destroys the sticker item structure and frees the pointer.
void * _d_json_to_sticker (cJSON *data)
Creates a sticker struct with the given JSON.
struct discord_sticker * _d_copy_sticker (struct discord_sticker *src)
Copies a sticker structure.
void discord_destroy_sticker (struct discord_sticker *sticker)
Destroys the sticker structure and frees the pointer.
Detailed Description
Sticker functions and structures.
Enumeration Type Documentation
Discord_Sticker_Format
enum Discord_Sticker_Format
Enumerator
STICKER_FORMAT_PNG
STICKER_FORMAT_APNG
STICKER_FORMAT_LOTTIE
Discord_Sticker_Type
enum Discord_Sticker_Type
Enumerator
STICKER_TYPE_STANDARD
STICKER_TYPE_GUILD
Function Documentation
_d_copy_sticker()
struct discord_sticker* _d_copy_sticker (struct discord_sticker * src)
Copies a sticker structure.
Parameters
src Sticker to copy.
Returns
struct discord_sticker*
Referenced by _d_copy_message().
_d_copy_sticker_item()
struct discord_message_sticker_item* _d_copy_sticker_item (struct discord_message_sticker_item * src)
Copies a sticker item structure.
Parameters
src Sticker item to copy.
Returns
struct discord_message_sticker_item*
Referenced by _d_copy_message().
_d_json_to_sticker()
void* _d_json_to_sticker (cJSON * data)
Creates a sticker struct with the given JSON.
Parameters
data
Returns
void*
Referenced by _d_json_to_message().
_d_json_to_sticker_item()
void* _d_json_to_sticker_item (cJSON * data)
Creates a sticker struct item with the given JSON.
Parameters
data
Returns
void*
Referenced by _d_json_to_message().
discord_destroy_message_sticker_item()
void discord_destroy_message_sticker_item (struct discord_message_sticker_item * message_sticker)
Destroys the sticker item structure and frees the pointer.
Parameters
sticker
Referenced by discord_destroy_message().
discord_destroy_sticker()
void discord_destroy_sticker (struct discord_sticker * sticker)
Destroys the sticker structure and frees the pointer.
Parameters
sticker
Referenced by discord_destroy_message().