Disco-C: Embed
Embed
Models
Data Structures
struct discord_embed_footer
https://discord.com/developers/docs/resources/channel#embed-object-embed-footer-structure
struct discord_embed_media
struct discord_embed_provider
https://discord.com/developers/docs/resources/channel#embed-object-embed-provider-structure
struct discord_embed_author
struct discord_embed_field
struct discord_embed
https://discord.com/developers/docs/resources/channel#embed-object
Functions
void * _d_json_to_embed_footer (cJSON *data)
Creates an embed_footer structure from a given JSON.
struct discord_embed_footer * _d_copy_embed_footer (struct discord_embed_footer *src)
Copies an embed footer structure.
void discord_destroy_embed_footer (struct discord_embed_footer *footer)
Destroys the given structure and frees the pointer.
void * _d_json_to_embed_media (cJSON *data)
Creates an embed_media structure from a given JSON.
struct discord_embed_media * _d_copy_embed_media (struct discord_embed_media *src)
Copies an embed media structure.
void discord_destroy_embed_media (struct discord_embed_media *media)
Destroys the given structure and frees the pointer.
void * _d_json_to_embed_provider (cJSON *data)
Creates an embed_provider structure from a given JSON.
struct discord_embed_provider * _d_copy_embed_provider (struct discord_embed_provider *src)
Copies an embed provider structure.
void discord_destroy_embed_provider (struct discord_embed_provider *provider)
Destroys the given structure and frees the pointer.
void * _d_json_to_embed_author (cJSON *data)
Creates an embed_author structure from a given JSON.
struct discord_embed_author * _d_copy_embed_author (struct discord_embed_author *src)
Copies an embed author structure.
void discord_destroy_embed_author (struct discord_embed_author *author)
Destroys the given structure and frees the pointer.
void * _d_json_to_embed_field (cJSON *data)
Creates an embed_field structure from a given JSON.
struct discord_embed_field * _d_copy_embed_field (struct discord_embed_field *src)
Copies an embed field structure.
void discord_destroy_embed_field (struct discord_embed_field *field)
Destroys the given structure and frees the pointer.
void * _d_json_to_embed (cJSON *data)
Creates an embed structure from a given JSON.
struct discord_embed * _d_copy_embed (struct discord_embed *src)
Copies an embed structure.
void discord_destroy_embed (struct discord_embed *embed)
Destroys the given structure and frees the pointer.
Detailed Description
Embed functions and structures
Function Documentation
_d_copy_embed()
struct discord_embed* _d_copy_embed (struct discord_embed * src)
Copies an embed structure.
Parameters
src Embed to copy.
Returns
struct discord_embed*
References _d_copy_embed_author(), _d_copy_embed_field(), _d_copy_embed_footer(), _d_copy_embed_media(), _d_copy_embed_provider(), discord_embed::author, discord_embed::description, discord_embed::fields, discord_embed::fields_count, discord_embed::footer, discord_embed::image, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed::url, and discord_embed::video.
Referenced by _d_copy_message().
_d_copy_embed_author()
struct discord_embed_author* _d_copy_embed_author (struct discord_embed_author * src)
Copies an embed author structure.
Parameters
src Embed author to copy.
Returns
struct discord_embed_author*
References discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by _d_copy_embed().
_d_copy_embed_field()
struct discord_embed_field* _d_copy_embed_field (struct discord_embed_field * src)
Copies an embed field structure.
Parameters
src Embed field to copy.
Returns
struct discord_embed_field*
References discord_embed_field::_inline, discord_embed_field::name, and discord_embed_field::value.
Referenced by _d_copy_embed().
_d_copy_embed_footer()
struct discord_embed_footer* _d_copy_embed_footer (struct discord_embed_footer * src)
Copies an embed footer structure.
Parameters
src Embed to copy.
Returns
struct discord_embed_footer*
References discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
Referenced by _d_copy_embed().
_d_copy_embed_media()
struct discord_embed_media* _d_copy_embed_media (struct discord_embed_media * src)
Copies an embed media structure.
Parameters
src Embed media to copy.
Returns
struct discord_embed_media*
References discord_embed_media::height, discord_embed_media::proxy_url, discord_embed_media::url, and discord_embed_media::width.
Referenced by _d_copy_embed().
_d_copy_embed_provider()
struct discord_embed_provider* _d_copy_embed_provider (struct discord_embed_provider * src)
Copies an embed provider structure.
Parameters
src Embed provider to copy.
Returns
struct discord_embed_provider*
References discord_embed_provider::name, and discord_embed_provider::url.
Referenced by _d_copy_embed().
_d_json_to_embed()
void* _d_json_to_embed (cJSON * data)
Creates an embed structure from a given JSON.
Parameters
data
Returns
void* discord_embed struct
References _d_get_array_from_json(), _d_get_int_from_json(), _d_get_string_from_json(), _d_json_to_embed_author(), _d_json_to_embed_field(), _d_json_to_embed_media(), _d_json_to_embed_provider(), discord_embed::author, discord_embed::color, discord_embed::description, discord_embed::fields, discord_embed::fields_count, discord_embed::footer, discord_embed::image, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed::url, and discord_embed::video.
_d_json_to_embed_author()
void* _d_json_to_embed_author (cJSON * data)
Creates an embed_author structure from a given JSON.
Parameters
data
Returns
void* discord_embed_author struct
References _d_get_string_from_json(), discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by _d_json_to_embed().
_d_json_to_embed_field()
void* _d_json_to_embed_field (cJSON * data)
Creates an embed_field structure from a given JSON.
Parameters
data
Returns
void* discord_embed_field struct
References _d_get_bool_from_json(), _d_get_string_from_json(), discord_embed_field::_inline, discord_embed_field::name, and discord_embed_field::value.
Referenced by _d_json_to_embed().
_d_json_to_embed_footer()
void* _d_json_to_embed_footer (cJSON * data)
Creates an embed_footer structure from a given JSON.
Parameters
data
Returns
void* discord_embed_footer struct
References _d_get_string_from_json(), discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
_d_json_to_embed_media()
void* _d_json_to_embed_media (cJSON * data)
Creates an embed_media structure from a given JSON.
Parameters
data
Returns
void* discord_embed_media struct
References _d_get_int_from_json(), _d_get_string_from_json(), discord_embed_media::height, discord_embed_media::proxy_url, discord_embed_media::url, and discord_embed_media::width.
Referenced by _d_json_to_embed().
_d_json_to_embed_provider()
void* _d_json_to_embed_provider (cJSON * data)
Creates an embed_provider structure from a given JSON.
Parameters
data
Returns
void* discord_embed_provider struct
References _d_get_string_from_json(), discord_embed_provider::name, and discord_embed_provider::url.
Referenced by _d_json_to_embed().
discord_destroy_embed()
void discord_destroy_embed (struct discord_embed * embed)
Destroys the given structure and frees the pointer.
Parameters
embed
References discord_embed::author, discord_embed::description, discord_destroy_embed_author(), discord_destroy_embed_field(), discord_destroy_embed_footer(), discord_destroy_embed_media(), discord_destroy_embed_provider(), discord_embed::fields, discord_embed::fields_count, discord_embed::footer, discord_embed::image, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed::url, and discord_embed::video.
Referenced by discord_destroy_message().
discord_destroy_embed_author()
void discord_destroy_embed_author (struct discord_embed_author * author)
Destroys the given structure and frees the pointer.
Parameters
author
References discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by discord_destroy_embed().
discord_destroy_embed_field()
void discord_destroy_embed_field (struct discord_embed_field * field)
Destroys the given structure and frees the pointer.
Parameters
field
References discord_embed_field::name, and discord_embed_field::value.
Referenced by discord_destroy_embed().
discord_destroy_embed_footer()
void discord_destroy_embed_footer (struct discord_embed_footer * footer)
Destroys the given structure and frees the pointer.
Parameters
footer
References discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
Referenced by discord_destroy_embed().
discord_destroy_embed_media()
void discord_destroy_embed_media (struct discord_embed_media * media)
Destroys the given structure and frees the pointer.
Parameters
media
References discord_embed_media::proxy_url, and discord_embed_media::url.
Referenced by discord_destroy_embed().
discord_destroy_embed_provider()
void discord_destroy_embed_provider (struct discord_embed_provider * provider)
Destroys the given structure and frees the pointer.
Parameters
provider
References discord_embed_provider::name, and discord_embed_provider::url.
Referenced by discord_destroy_embed().