Disco-C: Application
Application
Models
Application functions and structures.
Data Structures
struct discord_team_member
https://discord.com/developers/docs/topics/teams#data-models-team-member-object
struct discord_team
https://discord.com/developers/docs/topics/teams#data-models-team-object
struct discord_params
https://discord.com/developers/docs/resources/application#install-params-object
struct discord_application
https://discord.com/developers/docs/resources/application#application-object
Functions
void * _d_json_to_application (cJSON *data)
Creates an application structure from a given JSON.
struct discord_application * _d_copy_application (struct discord_application *src)
Copies a application structure.
void discord_destroy_application (struct discord_application *application)
Destroys the given structure and frees the pointer.
Detailed Description
Application functions and structures.
Function Documentation
_d_copy_application()
struct discord_application* _d_copy_application (struct discord_application * src)
Copies a application structure.
Parameters
src Application structure to copy.
Returns
struct discord_application*
Referenced by _d_copy_message().
_d_json_to_application()
void* _d_json_to_application (cJSON * data)
Creates an application structure from a given JSON.
Parameters
data
Returns
void* discord_application struct
Referenced by _d_json_to_message().
discord_destroy_application()
void discord_destroy_application (struct discord_application * application)
Destroys the given structure and frees the pointer.
Parameters
application
Referenced by discord_destroy_message().