Disco-C: Message_Activity
Message_Activity
Models
Data Structures
struct discord_message_activity
Enumerations
enum Discord_Message_Activity_Type { MESSAGE_ACTIVITY_JOIN = 1, MESSAGE_ACTIVITY_SPECTATE = 2, MESSAGE_ACTIVITY_LISTEN = 3, MESSAGE_ACTIVITY_JOIN_REQUEST = 5 }
Functions
void * _d_json_to_message_activity (cJSON *data)
Creates a message activity structure from a given JSON.
struct discord_message_activity * _d_copy_message_activity (struct discord_message_activity *activity)
Copies a message activity structure.
void discord_destroy_message_activity (struct discord_message_activity *activity)
Destroys the given structure.
Detailed Description
Message Activity functions and structures
Enumeration Type Documentation
Discord_Message_Activity_Type
enum Discord_Message_Activity_Type
Enumerator
MESSAGE_ACTIVITY_JOIN
MESSAGE_ACTIVITY_SPECTATE
MESSAGE_ACTIVITY_LISTEN
MESSAGE_ACTIVITY_JOIN_REQUEST
Function Documentation
_d_copy_message_activity()
struct discord_message_activity* _d_copy_message_activity (struct discord_message_activity * activity)
Copies a message activity structure.
Parameters
activity Message activity to copy.
Returns
struct discord_message_activity*
Referenced by _d_copy_message().
_d_json_to_message_activity()
void* _d_json_to_message_activity (cJSON * data)
Creates a message activity structure from a given JSON.
Parameters
data
Returns
void*
Referenced by _d_json_to_message().
discord_destroy_message_activity()
void discord_destroy_message_activity (struct discord_message_activity * activity)
Destroys the given structure.
Parameters
activity
Referenced by discord_destroy_message().