Disco-C: Channel
Channel
Models
Channel functions and structures.
Data Structures
struct discord_channel
https://discord.com/developers/docs/resources/channel#channel-object
struct discord_channel_mention
https://discord.com/developers/docs/resources/channel#channel-mention-object
Enumerations
enum Discord_Channel_Type {
CHANNEL_GUILD_TEXT = 0 , CHANNEL_DM = 1 , CHANNEL_GROUP_DM = 1 , CHANNEL_GUILD_VOICE = 2 ,
CHANNEL_GUILD_CATEGORY = 4 , CHANNEL_GUILD_NEWS = 5 , CHANNEL_GUILD_NEWS_THREAD = 10 , CHANNEL_GUILD_PUBLIC_THREAD = 11 ,
CHANNEL_GUILD_PRIVATE_THREAD = 12 , CHANNEL_GUILD_STAGE_VOICE = 13 , CHANNEL_GUILD_DIRECTORY = 14 , CHANNEL_GUILD_FORUM = 15
}
https://discord.com/developers/docs/resources/channel#channel-object-channel-types
Functions
void * _d_json_to_channel (cJSON *data)
Creates a channel structure from a given JSON.
struct discord_channel * _d_copy_channel (struct discord_channel *channel)
Copies a channel structure.
void discord_destroy_channel (struct discord_channel *ch)
Destroys the given structure and frees the pointer.
void * _d_json_to_channel_mention (cJSON *data)
Creates a channel_mention structure from a given JSON.
void discord_destroy_channel_mention (struct discord_channel_mention *ch)
Destroys the given structure and frees the pointer.
Detailed Description
Channel functions and structures.
Enumeration Type Documentation
Discord_Channel_Type
enum Discord_Channel_Type
https://discord.com/developers/docs/resources/channel#channel-object-channel-types
Enumerator
CHANNEL_GUILD_TEXT
CHANNEL_DM
CHANNEL_GROUP_DM
CHANNEL_GUILD_VOICE
CHANNEL_GUILD_CATEGORY
CHANNEL_GUILD_NEWS
CHANNEL_GUILD_NEWS_THREAD
CHANNEL_GUILD_PUBLIC_THREAD
CHANNEL_GUILD_PRIVATE_THREAD
CHANNEL_GUILD_STAGE_VOICE
CHANNEL_GUILD_DIRECTORY
CHANNEL_GUILD_FORUM
Function Documentation
_d_copy_channel()
struct discord_channel* _d_copy_channel (struct discord_channel * channel)
Copies a channel structure.
Parameters
channel Channel to copy.
Returns
struct discord_channel*
References _d_copy_overwrite(), _d_copy_thread_member(), _d_copy_thread_metadata(), _d_copy_user(), discord_channel::icon, discord_channel::last_pin_timestamp, discord_channel::member, discord_channel::name, discord_channel::permission_overwrites, discord_channel::permission_overwrites_count, discord_channel::permissions, discord_channel::recipients, discord_channel::recipients_count, discord_channel::rtc_region, discord_channel::thread_metadata, and discord_channel::topic.
Referenced by _d_copy_message(), and event_handle().
_d_json_to_channel()
void* _d_json_to_channel (cJSON * data)
Creates a channel structure from a given JSON.
Parameters
data
Returns
void* discord_channel struct
References _d_get_array_from_json(), _d_get_bool_from_json(), _d_get_int_from_json(), _d_get_long_from_string_json(), _d_get_string_from_json(), _d_json_to_overwrite(), _d_json_to_thread_member(), _d_json_to_thread_metadata(), _d_json_to_user(), discord_channel::application_id, discord_channel::bitrate, discord_channel::default_auto_archive_duration, discord_channel::flags, discord_channel::guild_id, discord_channel::icon, discord_channel::id, discord_channel::last_message_id, discord_channel::last_pin_timestamp, discord_channel::member, discord_channel::member_count, discord_channel::message_count, discord_channel::name, discord_channel::nsfw, discord_channel::owner_id, discord_channel::parent_id, discord_channel::permission_overwrites, discord_channel::permission_overwrites_count, discord_channel::permissions, discord_channel::position, discord_channel::rate_limit_per_user, discord_channel::recipients, discord_channel::recipients_count, discord_channel::rtc_region, discord_channel::thread_metadata, discord_channel::topic, discord_channel::type, discord_channel::user_limit, and discord_channel::video_quality_mode.
Referenced by event_handle().
_d_json_to_channel_mention()
void* _d_json_to_channel_mention (cJSON * data)
Creates a channel_mention structure from a given JSON.
Parameters
data
Returns
void* discord_channel_mention struct
References _d_get_int_from_json(), _d_get_long_from_string_json(), _d_get_string_from_json(), discord_channel_mention::guild_id, discord_channel_mention::id, discord_channel_mention::name, and discord_channel_mention::type.
Referenced by _d_json_to_message().
discord_destroy_channel()
void discord_destroy_channel (struct discord_channel * ch)
Destroys the given structure and frees the pointer.
Parameters
ch channel struct
References discord_destroy_overwrite(), discord_destroy_user(), discord_channel::icon, discord_channel::last_pin_timestamp, discord_channel::member, discord_channel::name, discord_channel::permission_overwrites, discord_channel::permission_overwrites_count, discord_channel::permissions, discord_channel::recipients, discord_channel::recipients_count, discord_channel::rtc_region, discord_channel::thread_metadata, and discord_channel::topic.
Referenced by default_destroy_callback(), and discord_destroy_message().
discord_destroy_channel_mention()
void discord_destroy_channel_mention (struct discord_channel_mention * ch)
Destroys the given structure and frees the pointer.
Parameters
ch channel_mention struct
References discord_channel_mention::name.