Disco-C: Emoji
Emoji
Models
Data Structures
struct discord_emoji
https://discord.com/developers/docs/resources/emoji#emoji-object
Functions
void * _d_json_to_emoji (cJSON *data)
Creates an emoji from a given JSON.
struct discord_emoji * _d_copy_emoji (struct discord_emoji *src)
Copies an emoji structure.
void discord_destroy_emoji (struct discord_emoji *emoji)
Destroys the given structure and frees the pointer.
Detailed Description
Emoji functions and structures
Function Documentation
_d_copy_emoji()
struct discord_emoji* _d_copy_emoji (struct discord_emoji * src)
Copies an emoji structure.
Parameters
src Emoji to copy.
Returns
struct discord_emoji*
Referenced by _d_copy_component(), and _d_copy_select_option().
_d_json_to_emoji()
void* _d_json_to_emoji (cJSON * data)
Creates an emoji from a given JSON.
Parameters
data
Returns
void* discord_emoji struct
Referenced by _d_json_to_component(), and _d_json_to_select_option().
discord_destroy_emoji()
void discord_destroy_emoji (struct discord_emoji * emoji)
Destroys the given structure and frees the pointer.
Parameters
emoji
Referenced by discord_destroy_component(), and discord_destroy_select_option().