Disco-C: src/discord/interaction.c File Reference
interaction.c File Reference
#include "structures/interaction.h"
#include "../utils/disco_logging.h"
#include "../web/request.h"
#include "disco.h"
#include <stdlib.h>
Functions
void * disco_create_interaction_data_option_struct_json (cJSON *data)
void disco_destroy_interaction_data_option (struct discord_interaction_data_option *o)
void * disco_create_interaction_data_struct_json (cJSON *data)
void disco_destroy_interaction_data (struct discord_interaction_data *interaction)
void * disco_create_interaction_struct_json (cJSON *data)
void disco_destroy_interaction (struct discord_interaction *interaction)
void disco_send_interaction (struct discord_interaction_callback *cb, struct discord_interaction *recv)
Function Documentation
disco_create_interaction_data_option_struct_json()
void* disco_create_interaction_data_option_struct_json (cJSON * data)
References COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, COMMAND_OPTION_STRING, disco_create_interaction_data_option_struct_json(), discord_interaction_data_option::double_, discord_interaction_data_option::focused, get_array_from_json(), get_bool_from_json(), get_double_from_string_json(), get_int_from_json(), get_string_from_json(), discord_interaction_data_option::int_, discord_interaction_data_option::name, discord_interaction_data_option::options, discord_interaction_data_option::options_count, discord_interaction_data_option::string_, discord_interaction_data_option::type, and discord_interaction_data_option::value.
Referenced by disco_create_interaction_data_option_struct_json(), and disco_create_interaction_data_struct_json().
disco_create_interaction_data_struct_json()
void* disco_create_interaction_data_struct_json (cJSON * data)
References discord_interaction_data::components, discord_interaction_data::components_count, discord_interaction_data::custom_id, disco_create_component_struct_json(), disco_create_interaction_data_option_struct_json(), disco_create_select_option_struct(), get_array_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_interaction_data::guild_id, discord_interaction_data::id, discord_interaction_data::name, discord_interaction_data::options, discord_interaction_data::options_count, discord_interaction_data::target_id, discord_interaction_data::type, discord_interaction_data::values, and discord_interaction_data::values_count.
Referenced by disco_create_interaction_struct_json().
disco_create_interaction_struct_json()
void* disco_create_interaction_struct_json (cJSON * data)
References discord_interaction::app_permissions, discord_interaction::application_id, discord_interaction::channel_id, discord_interaction::data, disco_create_interaction_data_struct_json(), disco_create_member_struct_json(), disco_create_message_struct_json(), disco_create_user_struct_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_interaction::guild_id, discord_interaction::guild_locale, discord_interaction::id, discord_interaction::locale, discord_interaction::member, discord_interaction::message, discord_interaction::token, discord_interaction::type, discord_interaction::user, and discord_interaction::version.
Referenced by disco_create_message_struct_json(), and event_handle().
disco_destroy_interaction()
void disco_destroy_interaction (struct discord_interaction * interaction)
References discord_interaction::app_permissions, discord_interaction::data, disco_destroy_interaction_data(), disco_destroy_member(), disco_destroy_message(), disco_destroy_user(), discord_interaction::guild_locale, discord_interaction::locale, discord_interaction::member, discord_interaction::message, discord_interaction::token, and discord_interaction::user.
Referenced by disco_destroy_message().
disco_destroy_interaction_data()
void disco_destroy_interaction_data (struct discord_interaction_data * interaction)
References discord_interaction_data::components, discord_interaction_data::components_count, discord_interaction_data::custom_id, disco_destroy_component(), disco_destroy_interaction_data_option(), discord_interaction_data::name, discord_interaction_data::options, discord_interaction_data::options_count, discord_interaction_data::values, and discord_interaction_data::values_count.
Referenced by disco_destroy_interaction().
disco_destroy_interaction_data_option()
void disco_destroy_interaction_data_option (struct discord_interaction_data_option * o)
References COMMAND_OPTION_STRING, disco_destroy_interaction_data_option(), discord_interaction_data_option::name, discord_interaction_data_option::options, discord_interaction_data_option::options_count, discord_interaction_data_option::string_, discord_interaction_data_option::type, and discord_interaction_data_option::value.
Referenced by disco_destroy_interaction_data(), and disco_destroy_interaction_data_option().
disco_send_interaction()
void disco_send_interaction (struct discord_interaction_callback * cb, struct discord_interaction * recv)
References discord_create_message::allowed_mentions, discord_create_message::attachments, discord_create_message::attachments_count, discord_interaction_callback::autocomplete, COMMAND_OPTION_INTEGER, COMMAND_OPTION_NUMBER, COMMAND_OPTION_STRING, discord_create_message::components, discord_create_message::components_count, d_log_debug, d_log_err, discord_interaction::data, discord_interaction_callback::data, DISCORD_CALLBACK_APPLICATION_COMMAND_AUTOCOMPLETE_RESULT, DISCORD_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE, DISCORD_CALLBACK_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE, DISCORD_CALLBACK_DEFERRED_UPDATE_MESSAGE, DISCORD_CALLBACK_MODAL, DISCORD_CALLBACK_PONG, DISCORD_CALLBACK_UPDATE_MESSAGE, discord_fill_json_with_component(), discord_fill_json_with_locales(), discord_fill_json_with_message(), discord_create_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, discord_interaction::id, discord_interaction_callback::message, discord_interaction_callback::modal, discord_interaction_data::options, request(), REQUEST_POST, discord_interaction::token, discord_create_message::tts, discord_interaction_data_option::type, and discord_interaction_callback::type.