Disco-C: src/discord/structures/message.h File Reference
message.h File Reference
#include "../disco.h"
#include "attachment.h"
#include "channel.h"
#include "component.h"
#include "embed.h"
#include "message_activity.h"
#include "reaction.h"
#include "sticker.h"
#include "user.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_allowed_mentions
struct discord_message_reference
struct discord_create_message
struct discord_message
Typedefs
typedef struct bot_client bot_client_t
Enumerations
enum discord_message_type {
DEFAULT, RECIPIENT_ADD, RECIPIENT_REMOVE, CALL,
CHANNEL_NAME_CHANGE, CHANNEL_ICON_CHANGE, CHANNEL_PINNED_MESSAGE, GUILD_MEMBER_JOIN,
USER_PREMIUM_GUILD_SUBSCRIPTION, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2, USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3,
CHANNEL_FOLLOW_ADD = 12, GUILD_DISCOVERY_DISQUALIFIED = 14, GUILD_DISCOVERY_REQUALIFIED, GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING,
GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING, THREAD_CREATED, REPLY, CHAT_INPUT_COMMAND,
THREAD_STARTER_MESSAGE, GUILD_INVITE_REMINDER, CONTEXT_MENU_COMMAND
}
Functions
void * disco_create_message_reference_struct_json (cJSON *data)
Creates a message_reference structure from a given JSON.
void disco_destroy_message_reference (struct discord_message_reference *message)
Destroys the given structure and frees the pointer.
void * disco_create_message_struct_json (cJSON *data)
Creates a message structure from a given JSON.
void disco_destroy_message (struct discord_message *message)
Destroys the given structure and frees the pointer.
void discord_fill_json_with_message (cJSON *json, char *content, struct discord_create_message *message)
Fills in a JSON with the attributes of the message structure.
struct discord_message * disco_channel_send_message (bot_client_t *bot, char *content, uint64_t channel_id, struct discord_create_message *message, bool return_struct)
Sends a message and if enabled also returns the sent message struct.
void disco_channel_edit_message (bot_client_t *bot, char *content, uint64_t channel_id, uint64_t message_id, struct discord_create_message *message)
Typedef Documentation
bot_client_t
typedef struct bot_client bot_client_t
Enumeration Type Documentation
discord_message_type
enum discord_message_type
Enumerator
DEFAULT
RECIPIENT_ADD
RECIPIENT_REMOVE
CALL
CHANNEL_NAME_CHANGE
CHANNEL_ICON_CHANGE
CHANNEL_PINNED_MESSAGE
GUILD_MEMBER_JOIN
USER_PREMIUM_GUILD_SUBSCRIPTION
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2
USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3
CHANNEL_FOLLOW_ADD
GUILD_DISCOVERY_DISQUALIFIED
GUILD_DISCOVERY_REQUALIFIED
GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING
GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING
THREAD_CREATED
REPLY
CHAT_INPUT_COMMAND
THREAD_STARTER_MESSAGE
GUILD_INVITE_REMINDER
CONTEXT_MENU_COMMAND
Function Documentation
disco_channel_edit_message()
void disco_channel_edit_message (bot_client_t * bot, char * content, uint64_t channel_id, uint64_t message_id, struct discord_create_message * message)
References discord_create_message::allowed_mentions, bot, discord_message::channel_id, discord_message::content, create_allowed_mentions(), create_embed_json(), d_log_debug, d_log_err, discord_create_message::embed, discord_create_message::embeds, discord_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, request(), and REQUEST_PATCH.
Referenced by example_on_message().
disco_channel_send_message()
struct discord_message* disco_channel_send_message (bot_client_t * bot, char * content, uint64_t channel_id, struct discord_create_message * message, bool return_struct)
Sends a message and if enabled also returns the sent message struct.
Parameters
bot Active bot instance
content Message content to send (if empty, embed or components need to exist)
channel_id ID of the channel the message should be sent in
message A discord_create_message struct. Can be NULL
return_struct Bool if the sent message should be returned or not (if yes, it has to be destroyed with disco_destroy_message() after)
Returns
struct discord_message* NULL or the struct of the sent message
References bot, discord_message::channel_id, discord_message::content, d_log_debug, d_log_err, disco_create_message_struct_json(), discord_fill_json_with_message(), request(), and REQUEST_POST.
Referenced by example_on_delete(), example_on_edit(), and example_on_message().
disco_create_message_reference_struct_json()
void* disco_create_message_reference_struct_json (cJSON * data)
Creates a message_reference structure from a given JSON.
Parameters
data
Returns
void* discord_message_reference struct
References discord_message_reference::channel_id, get_long_from_string_json(), discord_message_reference::guild_id, and discord_message_reference::message_id.
Referenced by disco_create_message_struct_json().
disco_create_message_struct_json()
void* disco_create_message_struct_json (cJSON * data)
Creates a message structure from a given JSON.
Parameters
data
Returns
void* discord_message struct
References discord_message::activity, discord_message::application, discord_message::application_id, discord_message::attachments, discord_message::attachments_count, discord_message::author, discord_message::channel_id, discord_message::components, discord_message::components_count, discord_message::content, discord_interaction::data, disco_create_application_struct_json(), disco_create_attachment_struct_json(), disco_create_channel_mention_struct_json(), disco_create_component_struct_json(), disco_create_interaction_struct_json(), disco_create_member_struct_json(), disco_create_message_activity_struct_json(), disco_create_message_reference_struct_json(), disco_create_message_sticker_item_struct_json(), disco_create_message_struct_json(), disco_create_reaction_struct_json(), disco_create_sticker_struct_json(), disco_create_user_struct_json(), discord_message::flags, get_array_from_json(), get_bool_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_message::guild_id, discord_message::id, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_everyone, discord_message::mention_roles, discord_message::mention_roles_count, discord_message::mentions, discord_message::mentions_count, discord_message::message_reference, discord_message::nonce, discord_message::pinned, discord_message::reactions, discord_message::reactions_count, discord_message::referenced_message, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::timestamp, discord_message::tts, discord_message::type, and discord_message::webhook_id.
Referenced by disco_channel_send_message(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), and event_handle().
disco_destroy_message()
void disco_destroy_message (struct discord_message * message)
Destroys the given structure and frees the pointer.
Parameters
message
References discord_message::activity, discord_message::application, discord_message::attachments, discord_message::attachments_count, discord_message::author, discord_message::components, discord_message::components_count, discord_message::content, disco_destroy_application(), disco_destroy_attachment(), disco_destroy_channel(), disco_destroy_component(), disco_destroy_embed(), disco_destroy_interaction(), disco_destroy_member(), disco_destroy_message_activity(), disco_destroy_message_reference(), disco_destroy_message_sticker(), disco_destroy_reaction(), disco_destroy_sticker(), disco_destroy_user(), discord_message::edited_timestamp, discord_message::embeds, discord_message::embeds_count, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_roles, discord_message::mentions, discord_message::mentions_count, discord_interaction::message, discord_message::message_reference, discord_message::nonce, discord_message::reactions, discord_message::reactions_count, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::thread, and discord_message::timestamp.
Referenced by default_destroy_callback(), disco_destroy_interaction(), and example_on_message().
disco_destroy_message_reference()
void disco_destroy_message_reference (struct discord_message_reference * message)
Destroys the given structure and frees the pointer.
Parameters
message
Referenced by disco_destroy_message().
discord_fill_json_with_message()
void discord_fill_json_with_message (cJSON * json, char * content, struct discord_create_message * message)
Fills in a JSON with the attributes of the message structure.
Parameters
json JSON struct that should be filled in with the values.
content Discord message content.
message Create message struct.
References discord_create_message::allowed_mentions, create_allowed_mentions(), create_embed_json(), create_message_reference(), discord_create_message::embed, discord_create_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, discord_create_message::message_reference, discord_create_message::sticker_ids, and discord_create_message::sticker_ids_count.
Referenced by disco_channel_send_message(), disco_send_interaction(), and test_message_creation().