Disco-C: src/discord/message.c File Reference
message.c File Reference
#include "structures/message.h"
#include "../utils/disco_logging.h"
#include "../web/request.h"
#include "structures/interaction.h"
#include <curl/curl.h>
#include <string.h>
Functions
static void embed_add_footer (cJSON *embed, struct discord_embed_footer *footer)
static void embed_add_media (cJSON *embed, struct discord_embed_media *media, char *media_type)
static void embed_add_author (cJSON *embed, struct discord_embed_author *author)
static void embed_add_field (cJSON *fields, struct discord_embed_field *field)
static cJSON * create_embed_json (struct discord_embed *embed)
static cJSON * create_allowed_mentions (struct discord_allowed_mentions *allowed_mentions)
static cJSON * create_message_reference (struct discord_message_reference *ref)
void discord_fill_json_with_message (cJSON *json, char *content, struct discord_create_message *message)
Fills in a JSON with the attributes of the message structure.
struct discord_message * disco_channel_send_message (bot_client_t *bot, char *content, uint64_t channel_id, struct discord_create_message *message, bool return_struct)
Sends a message and if enabled also returns the sent message struct.
void disco_channel_edit_message (bot_client_t *bot, char *content, uint64_t channel_id, uint64_t message_id, struct discord_create_message *message)
void * disco_create_message_struct_json (cJSON *data)
Creates a message structure from a given JSON.
void disco_destroy_message (struct discord_message *message)
Destroys the given structure and frees the pointer.
void * disco_create_message_reference_struct_json (cJSON *data)
Creates a message_reference structure from a given JSON.
void disco_destroy_message_reference (struct discord_message_reference *message)
Destroys the given structure and frees the pointer.
Function Documentation
create_allowed_mentions()
static cJSON* create_allowed_mentions (struct discord_allowed_mentions * allowed_mentions) static
References discord_create_message::allowed_mentions, discord_allowed_mentions::parse_everyone_mentions, discord_allowed_mentions::parse_role_mentions, discord_allowed_mentions::parse_user_mentions, discord_allowed_mentions::replied_user, discord_allowed_mentions::roles, discord_allowed_mentions::roles_count, discord_allowed_mentions::users, and discord_allowed_mentions::users_count.
Referenced by disco_channel_edit_message(), and discord_fill_json_with_message().
create_embed_json()
static cJSON* create_embed_json (struct discord_embed * embed) static
References discord_embed::author, discord_embed::color, discord_embed::description, discord_create_message::embed, embed_add_author(), embed_add_field(), embed_add_footer(), embed_add_media(), discord_embed::fields, discord_embed::fields_count, discord_embed::footer, discord_embed::image, discord_embed_provider::name, discord_embed::provider, discord_embed::thumbnail, discord_embed::timestamp, discord_embed::title, discord_embed::type, discord_embed_provider::url, discord_embed::url, and discord_embed::video.
Referenced by disco_channel_edit_message(), and discord_fill_json_with_message().
create_message_reference()
static cJSON* create_message_reference (struct discord_message_reference * ref) static
References discord_message_reference::channel_id, discord_message_reference::fail_if_not_exists, discord_message_reference::guild_id, and discord_message_reference::message_id.
Referenced by discord_fill_json_with_message().
disco_channel_edit_message()
void disco_channel_edit_message (bot_client_t * bot, char * content, uint64_t channel_id, uint64_t message_id, struct discord_create_message * message)
References discord_create_message::allowed_mentions, bot, discord_message::channel_id, discord_message::content, create_allowed_mentions(), create_embed_json(), d_log_debug, d_log_err, discord_create_message::embed, discord_create_message::embeds, discord_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, request(), and REQUEST_PATCH.
disco_channel_send_message()
struct discord_message* disco_channel_send_message (bot_client_t * bot, char * content, uint64_t channel_id, struct discord_create_message * message, bool return_struct)
Sends a message and if enabled also returns the sent message struct.
Parameters
bot Active bot instance
content Message content to send (if empty, embed or components need to exist)
channel_id ID of the channel the message should be sent in
message A discord_create_message struct. Can be NULL
return_struct Bool if the sent message should be returned or not (if yes, it has to be destroyed with disco_destroy_message() after)
Returns
struct discord_message* NULL or the struct of the sent message
References bot, discord_message::channel_id, discord_message::content, d_log_debug, d_log_err, disco_create_message_struct_json(), discord_fill_json_with_message(), request(), and REQUEST_POST.
disco_create_message_reference_struct_json()
void* disco_create_message_reference_struct_json (cJSON * data)
Creates a message_reference structure from a given JSON.
Parameters
data
Returns
void* discord_message_reference struct
References discord_message_reference::channel_id, get_long_from_string_json(), discord_message_reference::guild_id, and discord_message_reference::message_id.
Referenced by disco_create_message_struct_json().
disco_create_message_struct_json()
void* disco_create_message_struct_json (cJSON * data)
Creates a message structure from a given JSON.
Parameters
data
Returns
void* discord_message struct
References discord_message::activity, discord_message::application, discord_message::application_id, discord_message::attachments, discord_message::attachments_count, discord_message::author, discord_message::channel_id, discord_message::components, discord_message::components_count, discord_message::content, discord_interaction::data, disco_create_application_struct_json(), disco_create_attachment_struct_json(), disco_create_channel_mention_struct_json(), disco_create_component_struct_json(), disco_create_interaction_struct_json(), disco_create_member_struct_json(), disco_create_message_activity_struct_json(), disco_create_message_reference_struct_json(), disco_create_message_sticker_item_struct_json(), disco_create_message_struct_json(), disco_create_reaction_struct_json(), disco_create_sticker_struct_json(), disco_create_user_struct_json(), discord_message::flags, get_array_from_json(), get_bool_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_message::guild_id, discord_message::id, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_everyone, discord_message::mention_roles, discord_message::mention_roles_count, discord_message::mentions, discord_message::mentions_count, discord_message::message_reference, discord_message::nonce, discord_message::pinned, discord_message::reactions, discord_message::reactions_count, discord_message::referenced_message, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::timestamp, discord_message::tts, discord_message::type, and discord_message::webhook_id.
Referenced by disco_channel_send_message(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), and event_handle().
disco_destroy_message()
void disco_destroy_message (struct discord_message * message)
Destroys the given structure and frees the pointer.
Parameters
message
References discord_message::activity, discord_message::application, discord_message::attachments, discord_message::attachments_count, discord_message::author, discord_message::components, discord_message::components_count, discord_message::content, disco_destroy_application(), disco_destroy_attachment(), disco_destroy_channel(), disco_destroy_component(), disco_destroy_embed(), disco_destroy_interaction(), disco_destroy_member(), disco_destroy_message_activity(), disco_destroy_message_reference(), disco_destroy_message_sticker(), disco_destroy_reaction(), disco_destroy_sticker(), disco_destroy_user(), discord_message::edited_timestamp, discord_message::embeds, discord_message::embeds_count, discord_message::interaction, discord_message::member, discord_message::mention_channels, discord_message::mention_channels_count, discord_message::mention_roles, discord_message::mentions, discord_message::mentions_count, discord_interaction::message, discord_message::message_reference, discord_message::nonce, discord_message::reactions, discord_message::reactions_count, discord_message::sticker_items, discord_message::sticker_items_count, discord_message::stickers, discord_message::stickers_count, discord_message::thread, and discord_message::timestamp.
Referenced by default_destroy_callback(), and disco_destroy_interaction().
disco_destroy_message_reference()
void disco_destroy_message_reference (struct discord_message_reference * message)
Destroys the given structure and frees the pointer.
Parameters
message
Referenced by disco_destroy_message().
discord_fill_json_with_message()
void discord_fill_json_with_message (cJSON * json, char * content, struct discord_create_message * message)
Fills in a JSON with the attributes of the message structure.
Parameters
json JSON struct that should be filled in with the values.
content Discord message content.
message Create message struct.
References discord_create_message::allowed_mentions, create_allowed_mentions(), create_embed_json(), create_message_reference(), discord_create_message::embed, discord_create_message::embeds, discord_create_message::embeds_count, discord_create_message::flags, discord_create_message::message_reference, discord_create_message::sticker_ids, and discord_create_message::sticker_ids_count.
Referenced by disco_channel_send_message(), disco_send_interaction(), and test_message_creation().
embed_add_author()
static void embed_add_author (cJSON * embed, struct discord_embed_author * author) static
References discord_create_message::embed, discord_embed_author::icon_url, discord_embed_author::name, discord_embed_author::proxy_icon_url, and discord_embed_author::url.
Referenced by create_embed_json().
embed_add_field()
static void embed_add_field (cJSON * fields, struct discord_embed_field * field) static
References discord_embed_field::_inline, discord_embed_field::name, and discord_embed_field::value.
Referenced by create_embed_json().
embed_add_footer()
static void embed_add_footer (cJSON * embed, struct discord_embed_footer * footer) static
References discord_create_message::embed, discord_embed_footer::icon_url, discord_embed_footer::proxy_icon_url, and discord_embed_footer::text.
Referenced by create_embed_json().
embed_add_media()
static void embed_add_media (cJSON * embed, struct discord_embed_media * media, char * media_type) static
References discord_create_message::embed, discord_embed_media::height, discord_embed_media::proxy_url, discord_embed_media::url, and discord_embed_media::width.
Referenced by create_embed_json().