Disco-C: include/utils/prio_queue.h File Reference
prio_queue.h File Reference
#include <sys/time.h>
Data Structures
struct prio_node
struct prio_queue
Typedefs
typedef struct prio_node prio_node_t
Functions
void prio_init (struct prio_queue *queue)
prio_node_t * prio_push (struct prio_queue *queue, void *data, struct timeval wait_until)
prio_node_t * prio_pop (struct prio_queue *queue)
void prio_destroy_node (prio_node_t *node)
void prio_destroy_queue (struct prio_queue *queue)
Typedef Documentation
prio_node_t
typedef struct prio_node prio_node_t
Function Documentation
prio_destroy_node()
void prio_destroy_node (prio_node_t * node)
Referenced by prio_destroy_queue().
prio_destroy_queue()
void prio_destroy_queue (struct prio_queue * queue)
References prio_queue::head, prio_node::next, and prio_destroy_node().
Referenced by t_pool_destroy().
prio_init()
void prio_init (struct prio_queue * queue)
References prio_queue::head, and prio_queue::size.
Referenced by t_pool_init().
prio_pop()
prio_node_t* prio_pop (struct prio_queue * queue)
References prio_queue::head, and prio_queue::size.
Referenced by t_pool_pop_work().
prio_push()
prio_node_t* prio_push (struct prio_queue * queue, void * data, struct timeval wait_until)
References node::data, prio_queue::head, prio_node::next, prio_queue::size, and prio_node::wait_until.
Referenced by t_pool_add_work().