Disco-C: src/web/request.c File Reference
request.c File Reference
#include <discord/disco.h>
#include <libwebsockets.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <utils/disco_logging.h>
#include <utils/t_pool.h>
#include <web/request.h>
Data Structures
struct request_work_node
Functions
static size_t write_data (void *data, size_t s, size_t l, void *userp)
Callback function to write receiving data into a memory buffer.
struct curl_slist * setup_handle (CURL *handle, char *token)
static void request_t_pool (void *w, CURL *handle)
void request (char *url, cJSON *content, enum Request_Type request_type, const char *token, bot_client_t *bot, struct request_callback *rc)
Performs a HTTP request to the specified URL.
struct curl_slist * curl_setup_discord_header (CURL *h, const char *token)
Adds the correct Discord headers to a CURL handle.
Function Documentation
curl_setup_discord_header()
struct curl_slist* curl_setup_discord_header (CURL * handle, const char * token)
Adds the correct Discord headers to a CURL handle.
Parameters
handle
Returns
struct curl_slist*
References write_data().
Referenced by request_t_pool(), and setup_handle().
request()
void request (char * url, cJSON * content, enum Request_Type request_type, const char * token, bot_client_t * bot, struct request_callback * rc)
Performs a HTTP request to the specified URL.
Parameters
url URL to append to Discord Gateway
content Pointer to JSON that should be sent. If there's nothing to send, it should be NULL.
request_type The type of request to execute.
token The bot token.
rc The callback to execute if there is any.
Returns
long HTTP response code
References request_work_node::bot, request_work_node::iteration, request_work_node::json, request_work_node::rc, request_t_pool(), request_work_node::request_type, t_pool_add_work(), bot_client::thread_pool, request_work_node::token, and request_work_node::url.
Referenced by discord_channel_edit_message(), discord_channel_send_message(), discord_command_delete_global(), discord_command_delete_guild(), discord_command_register(), discord_command_update(), discord_fetch_message(), discord_get_messages(), and discord_send_interaction().
request_t_pool()
static void request_t_pool (void * w, CURL * handle) static
References _d_json_to_message(), request_work_node::bot, discord_message_cb::cb, discord_multiple_message_cb::cb, request_callback::cb_struct, curl_setup_discord_header(), d_log_err, d_log_info, discord_multiple_message_cb::data, discord_cache_set_message(), DISCORD_MESSAGE_CALLBACK, DISCORD_MULTIPLE_MESSAGE_CALLBACK, request_work_node::handle, request_work_node::http, request_work_node::iteration, request_work_node::json, request_work_node::rc, REQUEST_DELETE, REQUEST_GET, REQUEST_PATCH, REQUEST_POST, REQUEST_PUT, request_work_node::request_type, REQUEST_UPDATE, request_work_node::res, t_pool_add_work(), bot_client::thread_pool, request_work_node::token, request_callback::type, and request_work_node::url.
Referenced by request().
setup_handle()
struct curl_slist* setup_handle (CURL * handle, char * token)
References curl_setup_discord_header().
write_data()
static size_t write_data (void * data, size_t s, size_t l, void * userp) static
Callback function to write receiving data into a memory buffer.
Parameters
data Pointer to receiving memory
s Size (should always be 1)
l Size of receving memory
userp Pointer to memory chunk
Returns
size_t Amount written
References MemoryChunk::memory, and MemoryChunk::size.
Referenced by curl_setup_discord_header().