Disco-C: include/web/request.h File Reference
request.h File Reference
#include <cJSON/cJSON.h>
#include <curl/curl.h>
#include <discord/disco.h>
#include <string.h>
Data Structures
struct MemoryChunk
struct request_callback
Macros
#define VERBOSE 0
Enumerations
enum Request_Type {
REQUEST_GET , REQUEST_POST , REQUEST_PATCH , REQUEST_PUT ,
REQUEST_DELETE , REQUEST_UPDATE
}
enum Discord_Request_Callback_Type { DISCORD_MESSAGE_CALLBACK , DISCORD_MULTIPLE_MESSAGE_CALLBACK }
Functions
void request (char *url, cJSON *content, enum Request_Type request_type, const char *token, bot_client_t *bot, struct request_callback *rc, char **files, int files_n)
Performs a HTTP request to the specified URL.
int request_test (void)
Tests if request POST and GET work.
Macro Definition Documentation
VERBOSE
#define VERBOSE 0
Enumeration Type Documentation
Discord_Request_Callback_Type
enum Discord_Request_Callback_Type
Enumerator
DISCORD_MESSAGE_CALLBACK
DISCORD_MULTIPLE_MESSAGE_CALLBACK
Request_Type
enum Request_Type
Enumerator
REQUEST_GET
REQUEST_POST
REQUEST_PATCH
REQUEST_PUT
REQUEST_DELETE
REQUEST_UPDATE
Function Documentation
request()
void request (char * url, cJSON * content, enum Request_Type request_type, const char * token, bot_client_t * bot, struct request_callback * rc, char ** files, int files_n)
Performs a HTTP request to the specified URL.
Parameters
url URL to append to Discord Gateway
content Pointer to JSON that should be sent. If there's nothing to send, it should be NULL.
request_type The type of request to execute.
token The bot token.
rc The callback to execute if there is any.
Returns
long HTTP response code
References request_work_node::bot, request_work_node::files, request_work_node::files_n, request_work_node::iteration, request_work_node::json, request_work_node::rc, request_t_pool(), request_work_node::request_type, t_pool_add_work(), bot_client::thread_pool, request_work_node::token, and request_work_node::url.
Referenced by discord_channel_edit_message(), discord_channel_send_message(), discord_command_delete_global(), discord_command_delete_guild(), discord_command_register(), discord_command_update(), discord_fetch_message(), discord_get_messages(), and discord_send_interaction().
request_test()
int request_test (void)
Tests if request POST and GET work.
Returns
int 1 if it works, 0 else