Disco-C: src/discord/structures/sticker.h File Reference
sticker.h File Reference
#include "user.h"
#include <cJSON/cJSON.h>
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_message_sticker_item
struct discord_sticker
Enumerations
enum Discord_Sticker_Format { STICKER_FORMAT_PNG = 1, STICKER_FORMAT_APNG = 2, STICKER_FORMAT_LOTTIE = 3 }
enum Discord_Sticker_Type { STICKER_TYPE_STANDARD = 1, STICKER_TYPE_GUILD = 2 }
Functions
void * disco_create_message_sticker_item_struct_json (cJSON *data)
void disco_destroy_message_sticker (struct discord_message_sticker_item *message_sticker)
void * disco_create_sticker_struct_json (cJSON *data)
void disco_destroy_sticker (struct discord_sticker *sticker)
Enumeration Type Documentation
Discord_Sticker_Format
enum Discord_Sticker_Format
Enumerator
STICKER_FORMAT_PNG
STICKER_FORMAT_APNG
STICKER_FORMAT_LOTTIE
Discord_Sticker_Type
enum Discord_Sticker_Type
Enumerator
STICKER_TYPE_STANDARD
STICKER_TYPE_GUILD
Function Documentation
disco_create_message_sticker_item_struct_json()
void* disco_create_message_sticker_item_struct_json (cJSON * data)
Referenced by disco_create_message_struct_json().
disco_create_sticker_struct_json()
void* disco_create_sticker_struct_json (cJSON * data)
Referenced by disco_create_message_struct_json().
disco_destroy_message_sticker()
void disco_destroy_message_sticker (struct discord_message_sticker_item * message_sticker)
Referenced by disco_destroy_message().
disco_destroy_sticker()
void disco_destroy_sticker (struct discord_sticker * sticker)
Referenced by disco_destroy_message().