Disco-C: disco_event_callbacks Struct Reference
disco_event_callbacks Struct Reference
#include <disco.h>
Public Attributes
void(* on_ready)(bot_client_t *)
void(* on_resumed)(bot_client_t *)
void(* on_message)(bot_client_t *, struct discord_message *message)
void(* on_message_edit)(bot_client_t *, struct discord_message *old, struct discord_message *new)
void(* on_message_delete)(bot_client_t *, uint64_t message_id, uint64_t channel_id, uint64_t guild_id, struct discord_message *)
Function called if a message event is called. The message ID and channel ID are always given. If the message was sent in a guild, the guild ID is also included. If the message was in cache before being deleted, the message struct is also included.
void(* on_channel_create)(bot_client_t *, struct discord_channel *channel)
void(* on_channel_update)(bot_client_t *, struct discord_channel *old, struct discord_channel *new)
void(* on_channel_delete)(bot_client_t *, uint64_t channel_id, uint64_t guild_id, uint64_t parent_id, enum Discord_Channel_Type type, struct discord_channel *)
void(* on_interaction)(bot_client_t *, struct discord_interaction *)
Member Data Documentation
on_channel_create
void(* disco_event_callbacks::on_channel_create) (bot_client_t *, struct discord_channel *channel)
Referenced by event_handle(), event_handle_channel_create(), and main().
on_channel_delete
void(* disco_event_callbacks::on_channel_delete) (bot_client_t *, uint64_t channel_id, uint64_t guild_id, uint64_t parent_id, enum Discord_Channel_Type type, struct discord_channel *)
Referenced by event_handle(), event_handle_channel_delete(), and main().
on_channel_update
void(* disco_event_callbacks::on_channel_update) (bot_client_t *, struct discord_channel *old, struct discord_channel *new)
Referenced by event_handle(), event_handle_channel_update(), and main().
on_interaction
void(* disco_event_callbacks::on_interaction) (bot_client_t *, struct discord_interaction *)
Referenced by event_handle(), event_handle_interaction_create(), and main().
on_message
void(* disco_event_callbacks::on_message) (bot_client_t *, struct discord_message *message)
Referenced by event_handle(), event_handle_message_create(), and main().
on_message_delete
void(* disco_event_callbacks::on_message_delete) (bot_client_t *, uint64_t message_id, uint64_t channel_id, uint64_t guild_id, struct discord_message *)
Function called if a message event is called. The message ID and channel ID are always given. If the message was sent in a guild, the guild ID is also included. If the message was in cache before being deleted, the message struct is also included.
Referenced by event_handle(), event_handle_message_delete(), and main().
on_message_edit
void(* disco_event_callbacks::on_message_edit) (bot_client_t *, struct discord_message *old, struct discord_message *new)
Referenced by event_handle(), event_handle_message_update(), and main().
on_ready
void(* disco_event_callbacks::on_ready) (bot_client_t *)
Referenced by event_handle(), event_handle_ready(), and main().
on_resumed
void(* disco_event_callbacks::on_resumed) (bot_client_t *)
The documentation for this struct was generated from the following file:
src/discord/disco.h