Disco-C: src/utils/t_pool.c File Reference
t_pool.c File Reference
#include "t_pool.h"
#include "disco_logging.h"
#include <stdlib.h>
#include <sys/syscall.h>
#include <unistd.h>
Functions
static void * thread_work_loop (void *tp)
t_pool_t * t_pool_init (int num_t)
int t_pool_add_work (t_pool_t *tp, t_func func, void *arg)
Adds work to the thread pool.
t_work_t * t_pool_pop_work (t_pool_t *tp)
Pops the head of the pool and returns the pointer to the head. IMPORTANT: The received work needs to be freed to avoid memory leak! (Not thread-safe)
void t_pool_wait (t_pool_t *tp)
void t_pool_destroy (t_pool_t *tp)
int t_process_count (void)
Function Documentation
t_pool_add_work()
int t_pool_add_work (t_pool_t * tp, t_func func, void * work)
Adds work to the thread pool.
Parameters
tp
func
work
Returns
int
References t_work::arg, t_pool::first_work, t_work::func, t_pool::last_work, t_pool::lock, t_work::next, t_pool::work_cond, and t_pool::work_count.
Referenced by event_handle().
t_pool_destroy()
void t_pool_destroy (t_pool_t * tp)
References t_pool::finished_cond, t_pool::first_work, t_pool::lock, t_work::next, t_pool::stop, t_pool_wait(), t_pool::work_cond, and t_pool::work_count.
Referenced by disco_start_bot().
t_pool_init()
t_pool_t* t_pool_init (int num_t)
References t_pool::finished_cond, t_pool::first_work, t_pool::last_work, t_pool::lock, t_pool::stop, t_pool::thread_count, thread_work_loop(), t_pool::work_cond, and t_pool::work_count.
Referenced by disco_start_bot().
t_pool_pop_work()
t_work_t* t_pool_pop_work (t_pool_t * tp)
Pops the head of the pool and returns the pointer to the head. IMPORTANT: The received work needs to be freed to avoid memory leak! (Not thread-safe)
Parameters
tp
Returns
t_work_t*
References t_pool::first_work, t_pool::last_work, t_work::next, and t_pool::work_count.
Referenced by thread_work_loop().
t_pool_wait()
void t_pool_wait (t_pool_t * tp)
References t_pool::finished_cond, t_pool::lock, and t_pool::thread_count.
Referenced by t_pool_destroy().
t_process_count()
int t_process_count (void)
Referenced by disco_start_bot().
thread_work_loop()
static void* thread_work_loop (void * tp) static
References t_work::arg, t_pool::finished_cond, t_work::func, t_pool::lock, t_pool::stop, t_pool_pop_work(), t_pool::thread_count, t_pool::work_cond, and t_pool::work_count.
Referenced by t_pool_init().