Disco-C: include/utils/t_pool.h File Reference
t_pool.h File Reference
#include <curl/curl.h>
#include <pthread.h>
#include <stdbool.h>
#include <sys/time.h>
#include <utils/prio_queue.h>
Data Structures
struct t_work
struct t_pool
Typedefs
typedef void(* t_func) (void *, CURL *)
typedef struct t_work t_work_t
typedef struct t_pool t_pool_t
Functions
t_pool_t * t_pool_init (int num_t, const char *token)
Initializes the thread pool.
int t_pool_add_work (t_pool_t *tp, t_func func, void *work, struct timeval wait_until)
Adds work to the thread pool.
t_work_t * t_pool_pop_work (t_pool_t *tp)
Pops the head of the pool and returns the pointer to the head.
void t_pool_wait (t_pool_t *tp)
void t_pool_destroy (t_pool_t *tp)
int t_process_count (void)
Typedef Documentation
t_func
typedef void(* t_func) (void *, CURL *)
t_pool_t
typedef struct t_pool t_pool_t
t_work_t
typedef struct t_work t_work_t
Function Documentation
t_pool_add_work()
int t_pool_add_work (t_pool_t * tp, t_func func, void * work, struct timeval wait_until)
Adds work to the thread pool.
Parameters
tp
func
work
Returns
int
References t_work::arg, t_work::func, prio_queue::head, t_pool::lock, t_work::next, prio_push(), t_pool::queue, t_pool::sleep_until, prio_node::wait_until, t_work::wait_until, and t_pool::work_cond.
Referenced by request(), request_t_pool(), and thread_work_loop().
t_pool_destroy()
void t_pool_destroy (t_pool_t * tp)
References t_pool::finished_cond, prio_queue::head, t_pool::lock, prio_node::next, prio_destroy_queue(), t_pool::queue, t_pool::stop, t_pool_wait(), and t_pool::work_cond.
Referenced by discord_start_bot().
t_pool_init()
t_pool_t* t_pool_init (int num_t, const char * token)
Initializes the thread pool.
Parameters
num_t Number of threads to use for the thread pool.
token Bot token. Will be used to setup the CURL headers.
Returns
t_pool_t*
References t_pool::finished_cond, t_pool::lock, prio_init(), t_pool::queue, t_pool::stop, t_pool::thread_count, thread_work_loop(), t_pool::token, and t_pool::work_cond.
Referenced by discord_start_bot().
t_pool_pop_work()
t_work_t* t_pool_pop_work (t_pool_t * tp)
Pops the head of the pool and returns the pointer to the head.
IMPORTANT: The received work needs to be freed to avoid memory leak! (Not thread-safe)
Parameters
tp
Returns
t_work_t*
References node::data, prio_queue::head, prio_pop(), t_pool::queue, t_pool::sleep_until, and prio_node::wait_until.
Referenced by thread_work_loop().
t_pool_wait()
void t_pool_wait (t_pool_t * tp)
References t_pool::finished_cond, t_pool::lock, and t_pool::thread_count.
Referenced by t_pool_destroy().
t_process_count()
int t_process_count (void)
Referenced by discord_start_bot().