Disco-C: tests/test_discord.c File Reference
test_discord.c File Reference
#include "../src/discord/structures/component.h"
#include "../src/discord/structures/message.h"
#include "../src/utils/disco_logging.h"
#include <Unity/src/unity.h>
#include <stdbool.h>
Functions
void test_message_creation (void)
void test_embed_creation (void)
void setUp (void)
void tearDown (void)
int main (void)
Function Documentation
main()
int main (void)
References d_set_log_level(), and test_message_creation().
setUp()
void setUp (void)
tearDown()
void tearDown (void)
test_embed_creation()
void test_embed_creation (void)
test_message_creation()
void test_message_creation (void)
References discord_fill_json_with_message(), discord_create_message::flags, get_bool_from_json(), discord_create_message::sticker_ids, discord_create_message::sticker_ids_count, and discord_create_message::tts.
Referenced by main().