Disco-C: tests/test_web.c File Reference
test_web.c File Reference
#include "../src/discord/disco.h"
#include "../src/utils/disco_logging.h"
#include "../src/web/request.h"
#include "../src/web/websocket.h"
#include <Unity/src/unity.h>
Functions
void test_requests (void)
void websocket_on_receive (bot_client_t *bot, char *message, size_t len)
void test_websocket_create (void)
void test_websocket_connect (void)
void setUp (void)
void tearDown (void)
int main (void)
Variables
static bot_client_t bot = {0}
static websocket_client_t client = {0}
Function Documentation
main()
int main (void)
References d_set_log_level(), test_requests(), test_websocket_connect(), and test_websocket_create().
setUp()
void setUp (void)
References bot, client, and bot_client::websocket_client.
tearDown()
void tearDown (void)
test_requests()
void test_requests (void)
References request(), REQUEST_DELETE, REQUEST_GET, REQUEST_PATCH, REQUEST_POST, REQUEST_PUT, and REQUEST_UPDATE.
Referenced by main().
test_websocket_connect()
void test_websocket_connect (void)
References websocket_client::active, bot, bot_client::callbacks, client, websocket_client::connected, websocket_client::heartbeat_active, websocket_client::reconnect, websocket_client::success_login, bot_client::thread_pool, bot_client::user, bot_client::websocket_client, and websocket_connect().
Referenced by main().
test_websocket_create()
void test_websocket_create (void)
References websocket_client::active, client, websocket_client::connected, websocket_client::heartbeat_active, websocket_client::reconnect, websocket_client::success_login, websocket_create(), and websocket_on_receive().
Referenced by main().
websocket_on_receive()
void websocket_on_receive (bot_client_t * bot, char * message, size_t len)
References bot.
Referenced by test_websocket_create().
Variable Documentation
bot
bot_client_t bot = {0} static
Referenced by disco_channel_edit_message(), disco_channel_send_message(), disco_start_bot(), event_handle(), event_handle_ready(), gateway_event_loop(), gateway_handle_dispatch(), gateway_on_receive(), setUp(), test_websocket_connect(), and websocket_on_receive().
client
websocket_client_t client = {0} static
Referenced by disco_start_bot(), gateway_handle_identify(), gateway_heartbeat_loop(), gateway_send_heartbeat(), setUp(), test_websocket_connect(), test_websocket_create(), websocket_callback(), websocket_close(), websocket_create(), websocket_destroy_client(), and websocket_test().