Disco-C: src/discord/structures/user.h File Reference
user.h File Reference
#include <cJSON/cJSON.h>
#include <stdbool.h>
#include <stdint.h>
Classes
struct discord_user
struct discord_member
Functions
void * disco_create_user_struct_json (cJSON *data)
Creates a discod_user struct with the passed in JSON.
void disco_destroy_user (struct discord_user *user)
Destroys the discord_user structs and frees the passed in pointer.
void * disco_create_member_struct_json (cJSON *data, struct discord_user *user)
void disco_destroy_member (struct discord_member *member)
Function Documentation
disco_create_member_struct_json()
void* disco_create_member_struct_json (cJSON * data, struct discord_user * user)
Referenced by disco_create_interaction_struct_json(), and disco_create_message_struct_json().
disco_create_user_struct_json()
void* disco_create_user_struct_json (cJSON * data)
Creates a discod_user struct with the passed in JSON.
Parameters
data The Discord JSON for a user
Returns
struct discord_user*
References discord_user::accent_color, discord_user::avatar, discord_user::banner, discord_user::bot, discord_user::discriminator, discord_user::email, discord_user::flags, get_bool_from_json(), get_int_from_json(), get_long_from_string_json(), get_string_from_json(), discord_user::id, discord_user::locale, discord_user::mfa_enabled, discord_user::premium_type, discord_user::public_flags, discord_user::system, discord_user::username, and discord_user::verified.
Referenced by disco_create_channel_struct_json(), disco_create_interaction_struct_json(), disco_create_message_struct_json(), and event_handle().
disco_destroy_member()
void disco_destroy_member (struct discord_member * member)
Referenced by disco_destroy_interaction(), and disco_destroy_message().
disco_destroy_user()
void disco_destroy_user (struct discord_user * user)
Destroys the discord_user structs and frees the passed in pointer.
Parameters
user
References discord_user::avatar, discord_user::banner, discord_user::discriminator, discord_user::email, discord_user::locale, and discord_user::username.
Referenced by disco_destroy_channel(), disco_destroy_interaction(), disco_destroy_message(), disco_start_bot(), and event_handle().