Disco-C: include/web/websocket.h File Reference
websocket.h File Reference
#include <curl/curl.h>
#include <discord/disco.h>
#include <libwebsockets.h>
Data Structures
struct websocket_callbacks
struct websocket_client
Typedefs
typedef struct bot_client bot_client_t
typedef void(* callback_receive_fn) (struct bot_client *, char *, size_t)
typedef struct websocket_client websocket_client_t
Functions
int websocket_send (struct lws *wsi, char *data, size_t len)
Sends data through the websocket connection.
int websocket_create (websocket_client_t *client, callback_receive_fn on_receive)
Sets up the websocket client.
int websocket_connect (bot_client_t *bot_client)
Sends the initial handshake to connect to the Discord websocket The client is only marked as "connected" once an answer from Discord is received.
void websocket_exit (bot_client_t *bot_client)
Exits the websocket connection completely.
void websocket_close (bot_client_t *bot_client)
Requests the websocket to close If the exit flag is not set this will result in a reconnect.
void websocket_reconnect (bot_client_t *bot_client)
Reconnects to the websocket.
void websocket_destroy_client (websocket_client_t *client)
Frees up all memory allocated with the bot_client struct.
int websocket_test (void)
Typedef Documentation
bot_client_t
typedef struct bot_client bot_client_t
callback_receive_fn
typedef void(* callback_receive_fn) (struct bot_client *, char *, size_t)
websocket_client_t
typedef struct websocket_client websocket_client_t
Function Documentation
websocket_close()
void websocket_close (bot_client_t * bot_client)
Requests the websocket to close If the exit flag is not set this will result in a reconnect.
Parameters
bot_client
References client, websocket_client::context, websocket_client::heartbeat_active, websocket_client::heartbeat_thread, bot_client::websocket_client, and websocket_client::wsi.
Referenced by websocket_callback(), websocket_exit(), and websocket_reconnect().
websocket_connect()
int websocket_connect (bot_client_t * bot_client)
Sends the initial handshake to connect to the Discord websocket The client is only marked as "connected" once an answer from Discord is received.
Parameters
bot_client Bot client instance
Returns
int
References websocket_client::active, websocket_client::content, websocket_client::context, port, websocket_client::size, ssl_connection, bot_client::websocket_client, and websocket_client::wsi.
Referenced by discord_start_bot(), test_websocket_connect(), and websocket_callback().
websocket_create()
int websocket_create (websocket_client_t * client, callback_receive_fn on_receive)
Sets up the websocket client.
Parameters
client Pointer to a websocket client
on_receive Callback function for the receiving websocket packages
Returns
int
References websocket_client::active, websocket_client::callbacks, client, websocket_client::connected, websocket_client::context, websocket_client::exit, websocket_client::heartbeat_active, websocket_callbacks::on_receive, protocols, and websocket_client::success_login.
Referenced by discord_start_bot(), test_websocket_create(), and websocket_test().
websocket_destroy_client()
void websocket_destroy_client (websocket_client_t * client)
Frees up all memory allocated with the bot_client struct.
Parameters
client Websocket client that should be destroyed
References websocket_client::active, websocket_client::callbacks, client, websocket_client::connected, websocket_client::content, websocket_client::context, websocket_client::heartbeat_active, websocket_client::heartbeat_thread, and websocket_client::wsi.
Referenced by discord_start_bot().
websocket_exit()
void websocket_exit (bot_client_t * bot_client)
Exits the websocket connection completely.
Parameters
bot_client
References websocket_client::exit, bot_client::websocket_client, and websocket_close().
websocket_reconnect()
void websocket_reconnect (bot_client_t * bot_client)
Reconnects to the websocket.
Parameters
bot_client
References websocket_close().
Referenced by gateway_on_receive().
websocket_send()
int websocket_send (struct lws * wsi, char * data, size_t len)
Sends data through the websocket connection.
Parameters
wsi Websocket connection
data Data to send
len Length of data to send
Returns
int
Referenced by gateway_handle_identify(), and gateway_send_heartbeat().
websocket_test()
int websocket_test (void)
References websocket_client::active, client, websocket_client::context, sigint_handler(), and websocket_create().