Disco-C: src/web/websocket.c File Reference
websocket.c File Reference
#include <curl/curl.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <web/websocket.h>
Functions
static int websocket_callback (struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)
int websocket_create (websocket_client_t *client, callback_receive_fn on_receive)
Sets up the websocket client.
int websocket_connect (bot_client_t *bot_client)
Sends the initial handshake to connect to the Discord websocket The client is only marked as "connected" once an answer from Discord is received.
void websocket_destroy_client (websocket_client_t *client)
Frees up all memory allocated with the bot_client struct.
int websocket_send (struct lws *wsi, char *data, size_t len)
Sends data through the websocket connection.
void websocket_reconnect (bot_client_t *bot_client)
Reconnects to the websocket.
void websocket_close (bot_client_t *bot_client)
Closes the websocket connection and sends a normal close reason to the websocket server reason.
static void sigint_handler (int sig)
int websocket_test (void)
Variables
static int port = 443
static int ssl_connection = 1
static const struct lws_protocols protocols []
Function Documentation
sigint_handler()
static void sigint_handler (int sig) static
Referenced by websocket_test().
websocket_callback()
static int websocket_callback (struct lws * wsi, enum lws_callback_reasons reason, void * user, void * in, size_t len) static
References websocket_client::active, websocket_client::callbacks, client, websocket_client::connected, websocket_client::content, websocket_callbacks::on_receive, websocket_client::reconnect, websocket_client::size, websocket_client::success_login, bot_client::websocket_client, websocket_close(), and websocket_connect().
websocket_close()
void websocket_close (bot_client_t * bot_client)
Closes the websocket connection and sends a normal close reason to the websocket server reason.
Parameters
bot_client
References client, websocket_client::context, websocket_client::heartbeat_active, websocket_client::heartbeat_thread, bot_client::websocket_client, and websocket_client::wsi.
Referenced by websocket_callback(), and websocket_reconnect().
websocket_connect()
int websocket_connect (bot_client_t * bot_client)
Sends the initial handshake to connect to the Discord websocket The client is only marked as "connected" once an answer from Discord is received.
Parameters
bot_client Bot client instance
Returns
int
References websocket_client::active, websocket_client::content, websocket_client::context, port, websocket_client::size, ssl_connection, bot_client::websocket_client, and websocket_client::wsi.
Referenced by discord_start_bot(), test_websocket_connect(), and websocket_callback().
websocket_create()
int websocket_create (websocket_client_t * client, callback_receive_fn on_receive)
Sets up the websocket client.
Parameters
client Pointer to a websocket client
on_receive Callback function for the receiving websocket packages
Returns
int
References websocket_client::active, websocket_client::callbacks, client, websocket_client::connected, websocket_client::context, websocket_client::heartbeat_active, websocket_callbacks::on_receive, protocols, and websocket_client::success_login.
Referenced by discord_start_bot(), test_websocket_create(), and websocket_test().
websocket_destroy_client()
void websocket_destroy_client (websocket_client_t * client)
Frees up all memory allocated with the bot_client struct.
Parameters
client Websocket client that should be destroyed
References websocket_client::active, websocket_client::callbacks, client, websocket_client::connected, websocket_client::content, websocket_client::context, websocket_client::heartbeat_active, websocket_client::heartbeat_thread, and websocket_client::wsi.
Referenced by discord_start_bot().
websocket_reconnect()
void websocket_reconnect (bot_client_t * bot_client)
Reconnects to the websocket.
Parameters
bot_client
References websocket_client::reconnect, bot_client::websocket_client, and websocket_close().
Referenced by gateway_on_receive().
websocket_send()
int websocket_send (struct lws * wsi, char * data, size_t len)
Sends data through the websocket connection.
Parameters
wsi Websocket connection
data Data to send
len Length of data to send
Returns
int
Referenced by gateway_handle_identify(), and gateway_send_heartbeat().
websocket_test()
int websocket_test (void)
References websocket_client::active, client, websocket_client::context, sigint_handler(), and websocket_create().
Variable Documentation
port
int port = 443 static
Referenced by websocket_connect().
protocols
const struct lws_protocols protocols[] static
Initial value:
= {
    {"discord-gateway", websocket_callback, 0, 0, 0, NULL, 0},
    {NULL, NULL, 0, 0, 0, NULL, 0}}
Referenced by websocket_create().
ssl_connection
int ssl_connection = 1 static
Referenced by websocket_connect().