name: Wiki Setup

on:
  push:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Install
        run: |
          sudo apt update
          sudo apt install doxygen graphviz python3-sphinx
          pip3 install sphinx-press-theme
          wget https://github.com/vovkos/doxyrest/releases/download/doxyrest-2.1.3/doxyrest-2.1.3-linux-x86.tar.xz
          tar -xf doxyrest-2.1.3-linux-x86.tar.xz
          
      - name: Generate Doxygen
        run: doxygen Doxygen/Doxyfile
      
      - name: Doxyrest
        run: ./doxyrest-2.1.3-linux-x86/bin/doxyrest -c Doxygen/doxyrest-config.lua
      
      - name: Sphinx
        run: sphinx-build -b html rst-dir html-dir
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: wiki
          publish_dir: ./generated-docs/html-dir
