name: Wiki Setup

on:
  push:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Install
        run: |
          sudo apt update
          sudo apt install doxygen graphviz python3-sphinx expat liblua5.2-0
          pip3 install sphinx-press-theme
          wget https://github.com/vovkos/doxyrest/releases/download/doxyrest-2.1.3/doxyrest-2.1.3-linux-amd64.tar.xz -O doxyrest.tar.xz
          tar -xf doxyrest.tar.xz
          # This renames the unzipped doxyrest folder to simply doxyrest
          for x in doxyrest-[0-9]*; do mv "$x" doxygen; done
          
      - name: Generate Doxygen
        run: doxygen docs/Doxyfile
      
      - name: Doxyrest
        run: ./doxyrest/bin/doxyrest -c docs/doxyrest-config.lua
      
      - name: Sphinx
        run: sphinx-build -b html rst-dir html-dir -c docs
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: wiki
          publish_dir: ./generated-docs/html-dir
